### ISSUE TITLE
Usage of github topics

### ISSUE THREAD

**Issue by devinivy** [hapijs/contrib#105]
Github released a new "topics" feature today ([see here](https://github.com/blog/2309-introducing-topics)).  In short,
> Topics are labels that create subject-based connections between GitHub repositories and let you explore projects by type, technology, and more.

We have the option of tagging our repos with topics.  A few questions come to mind,
 - Should we participate in this at all?
 - Should we declare a specific topic as being "hapi-official"?  E.g. saying the hapi topic is `hapijs`, versus `hapi`.  This might also be useful for others trying to decide how to label and search for hapi-related repos.
 - If we do participate in topics, what topics should we use on repos within this org?
 - Would we consider more specific topics, such as `hapi-plugin`, `hapi-good` (e.g. for good's logging adapters), `hapi-catbox` (e.g. for catbox's storage adapters), `hapi-core` (e.g. for direct dependencies of hapi), etc.?

My opinion is that at minimum it would be useful to decide on hapi's topic as being `hapi` or `hapijs`, and make it known to plugin/tooling authors via hapijs.com.

**Comment by AdriVanHoudt** [comment]
I think we should go with `hapijs` as to label it with `good` or `hapi-good`, I have slight preference to `good`. 
Maybe in general they should include the `package.json`'s keywords?

**Comment by Marsup** [comment]
I went with hapi and all others already set in the package.json keywords. I don't really see the value in it as all of my discovery process is based on npm, which is why I went for the least effort.

**Comment by AdriVanHoudt** [comment]
I have seen `hapi` being used as well elsewhere...
@Marsup the question is will people and/or google use these topics to look for plugins

Can we query github for repos with certain topics? If so it might be feasible to auto populate the plugin section on the website /cc @nlf
