### ISSUE TITLE
npm org and sharing access

### ISSUE THREAD

**Issue by nlf** [hapijs/contrib#109]
As of today, we have created an [npm org](https://npmjs.com/org/hapi) and begun adding the majority of the published modules in the hapijs github org to it. We are intentionally leaving out hapi itself, as well as any modules that have been flagged as deprecated.

The main goal here is to make sure that at least a small number of people have access to publish each module in the event that a new maintainer has to be sought out and we're unable to contact the current one. Currently only a small number of people have been given access, however we may change that to include the other core contributors or some subset of them.

I'm opening this issue in the interest of transparency and so we can discuss the merits and concerns of sharing or not sharing this access with a greater number of people.

**Comment by cjihrig** [comment]
Is it too late to change the npm org name to hapijs to match the github name?

**Comment by nlf** [comment]
we actually have both orgs, we've just added the packages to the hapi one. i'm completely neutral on the matter, but that's a reasonable point.

**Comment by AdriVanHoudt** [comment]
Hapijs makes more sense since the GitHub org has that name and what is the exact reason to let hapi itself out of it?

**Comment by nlf** [comment]
keeping hapi itself out of the org maintains its access to only the lead maintainer (Eran), that's not something we intend to change. this is about allowing the lead maintainer, the community lead, and potentially other core contributors to facilitate maintainer handoffs (and interim publishes) for the other modules in the hapi ecosystem.

**Comment by AdriVanHoudt** [comment]
hmm no way to make exceptions inside npm? if so then fine 👍

**Comment by devinivy** [comment]
This all sounds good 👍 I'd love it if the github and npm org names matched!

**Comment by hueniverse** [comment]
Keep in mind the npm org name is just for admin purposes. Unlike the GitHub org, no one should care about the npm one unless you are handling access admin.
