### ISSUE TITLE
Community CI service

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#11]
The hapi ecosystem is getting big, much bigger than anyone can keep track of. This is particularity true for hapi itself. It is becoming very hard to ensure that changes which pass all the hapi tests, are not breaking other modules, including tightly coupled ones like inert (file and directory handlers), h2o2 (proxy handlers), and vision (views engine).

It would be awesome is someone(s) will take on the project of building a community service where people can register their open source work, and every time there is an update (publish or commit, open for debate) on any of the core framework modules, it will test those out.

Some of these projects can be nothing but tests to ensure your private code will not break without exposing it.

The npm package **popular** is still available...

**Comment by DavidTPate** [comment]
It looks like this could be handled with Travis here shortly based on travis-ci/travis-ci#249

It'd be really nice to use their infrastructure instead of having to maintain a set of infrastructure/code to handle this.
