### ISSUE TITLE
New core contributor - Gil Pedersen

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#111]
@kanongil has taken over catbox and ammo and has joined as a full core contributor member. Please join me in thanking Gil for his new commitment and future contributions.

**Comment by Marsup** [comment]
Ha, I thought he already was, welcome again :)

**Comment by kanongil** [comment]
@Marsup Thanks – I used to be until inert was removed from core. It's nice to be back 😃

**Comment by AdriVanHoudt** [comment]
Thought the same as @Marsup 😆 
A very big welcome 🎆

**Comment by sirgallifrey** [comment]
Congrats @kanongil :cake: :birthday: :tada: :balloon:

**Comment by devinivy** [comment]
That's awesome news– welcome back to core @kanongil :)

P.S. seems like a good time to say, your contributions to hapi are top notch.  You've really pushed hapi's tightness and stability, and I appreciate that a lot!

**Comment by johnbrett** [comment]
Congrats @kanongil! Great to have you back 👍
