### ISSUE TITLE
Propose renaming "new contributor" label to "good first issue"

### ISSUE THREAD

**Issue by devinivy** [hapijs/contrib#123]
In the [guidelines doc](https://github.com/hapijs/contrib/blob/master/Guidelines.md#labels) the `new contributor` label is described as such,
> tasks that are sufficiently small and easy for new contributors to complete, and which collaborators don't mind assisting new contributors in completing.

This seems to be very much in line with a label officially recognized by github named `good first issue`.  Issues with this label are better surfaced to potential new contributors (see [here](https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/)).  Same goes for `help wanted`, which we already have.  I propose we simply rename `new contributor` to `good first issue` in order to take advantage of github's preference for this label name, and in an effort to be just a little more standard.  If we would like to do this and @Marsup will have it, I would be open to providing a PR to [hil](https://github.com/Marsup/hil) to help maintainers automate the update.

**Comment by Nargonath** [comment]
Good call @devinivy!

**Comment by hueniverse** [comment]
Sure. Go ahead and change them...

**Comment by devinivy** [comment]
Well, that was easy!  @Marsup thanks for the headsup.  I ended-up not using hil for the migration, and hil should work fine going forward.  Thanks for the quick merge and publish.  I have updated the label name on all repos, so no further action is required by maintainers.
