### ISSUE TITLE
MrHorse: new contrib module

### ISSUE THREAD

**Issue by mark-bradshaw** [hapijs/contrib#13]
https://github.com/mark-bradshaw/mrhorse

I'd like to offer a new module to be included as a hapi contrib module.  It's called MrHorse ("No sir, I don't like it") since it was originally conceived to help with authorization tasks.  This was inspired by policies in the sailsjs project, but is more flexible, IMO.  Policies in sails are basically for authentication and authorization only, but MrHorse can do just about any task that isn't specific to a particular route handler.

The idea of MrHorse is to allow you to take commonly repeated bits of code out of route handlers and centralize them in a "policy" to DRY up your code.  Then, in accordance with hapi's configuration driven goals, you can assign that policy to any route that needs it.

The policy can run as either a pre or post handler, so you can use it to do authentication, authorization, data prefetching, etc. before your route handler gets executed, or you can do response modification, logging, etc after it is finished.  It's extremely flexible.

Only one policy can live in a single file, but you can have multiple policies directories.  So each plugin in your hapi app can have its own directory of policies.  Or you can have a central policy directory.

Probably the best feature of using MrHorse and policies is that you can look at your routing setup and immediately tell which routes are getting bits of business logic run on them.  Say you have a policy that does authorization checks to make sure a route is only accessible to admins, called "isAdmin".  One glance at your route entries and you can see immediately which routes have that policy applied.

It looks like this:

```
server.route({
    method: 'GET',
    path: '/loggedin',
    handler: function(request, reply) {},
    config: {
        plugins: {
            policies: ['isLoggedIn']
        }
    }
});

server.route({
    method: 'GET',
    path: '/admin',
    handler: function(request, reply) {},
    config: {
        plugins: {
            policies: ['isLoggedIn', 'isAnAdmin']
        }
    }
});
```

In my projects I've used it for authentication, authorization, response modification, and logging.  The flexibility of the system is very useful.  Take a look and let me know if you want to pull it in.  I'm open to renaming it.

https://github.com/mark-bradshaw/mrhorse

**Comment by paulovieira** [comment]
Speaking as a end-user, I think post-requisites would be a natural and useful addition to hapi.

This would be the right place to do stuff like this:

 - close database connections
 - apply Hoek.transform to format the object / array of objects of the response (delete some properties, move properties from nested objectes to the top object, etc)

Essentially, post-requisites would be the place where common post-processing utilities would be used.

The plugin fills this need partially. Having this functionality available directly in Hapi would be perfect.

**Comment by devinivy** [comment]
For a more native hapi feel (specifically for post-requisites), I've pulled-together https://github.com/devinivy/loveboat-postreqs.  This takes advantage of route-level request extensions, which is something mrhorse cannot currently do (because there is no programmatic API for adding route-level extensions).

**Comment by juanjoLenero** [comment]
I just want to share my use case in support of `post-requisites`.

We are storing "translatable" fields as a json object in out database:
```js
// A payload ready to be inserted to a database.
{
    title: { "en": "My title" },
    description: { "en": "My description" }
}
```

We want to handle this transparently to the clients, this is what a client would send to the server:
```
POST /places 
Accept-Language: en
title=My title 
description=My description
```

We can tranform from client version -> database version with a `pre-requisite` like this:
```
server.route({
    method: 'POST',
    path: '/places',
    config: {
        pre: [
            // title: 'My title' -> title: { lang: 'My title' }
            { method: Lang.toTranslatable(['title', 'description']) }
        ],
        handler: function (request, reply) {

            return reply(Place.query().insertAndFetch(request.payload));
        }
    }
});
```

After the database inserts the record, we need to transform the data back into the client version.
I think this will work perfectly with `post-requisites` like this:
```
pre: [
    // title: 'My title' -> title: { lang: 'My title' }
    { method: Lang.toTranslatable(['title', 'description']) }
],
post: [
    // title: { lang: 'My title' } -> title: 'My title'.
    { method: Lang.fromTranslatable(['title', 'description']) }
]
```
I think this would be a very clean and maintainable way to share this functionality between all the routes that accept and respond with "translatable" fields.

**Comment by nlf** [comment]
your use case feels like what [reply decorators](http://hapijs.com/api#serverdecoratetype-property-method-options) are for. instead of using a post-requisite, create a reply decorator so you'd do something like `reply.translate(Place.query().insertAndFetch(request.payload))`

**Comment by devinivy** [comment]
@juanjoLenero today you can also use the `ext` route config to add `onPostHandler` extensions per-route.  This is codified into a module [here](https://github.com/devinivy/loveboat-postreqs), but in lieu of actually adopting loveboat (which is no small deal), you might look at the logic used internally to the module to make adding post-requisites simpler.

**Comment by juanjoLenero** [comment]
@nlf That works, but I think it would quickly become unmanageable `reply.translateAndCleanSensitiveAndSomethingElse(...)` whereas with the `post-requisites` option you would:
```js
post: [
    { method: Lang.fromTranslatable(['title', 'description']) },
    { method: Security.cleanSensitive(['password', 'token']) },
    ...
]
```

@devinivy Thank you, I was evaluating`loveboat` just now, I'll take your advise and look at the internals to see how per-route onPostHandlers work.

**Comment by juanjoLenero** [comment]
Just wanted to comment back to say that may use case is handled by `route-level extensions` like so:
```js
ext: {
    onPostHandler: [
        { method: Lang.fromTranslatable(['title', 'description']) }
    ]
}
```
Can someone comment on why I would use `pre-requisites` intead of `onPreHandler` extension point like this:
```js
ext: {
    onPreHandler: [
        { method: Lang.toTranslatable(['title', 'description']) }
    ],
    onPostHandler: [
        { method: Lang.fromTranslatable(['title', 'description']) }
    ]
}
```

**Comment by devinivy** [comment]
Yes, pre-requisites are tied closer to the handler than `onPreHandler`.  Additionally, their results are placed in `request.pre`, they can be configured to easily run in series and in parallel, and they accept special string options that integrate with server methods.
