### ISSUE TITLE
Display sponsors somewhere

### ISSUE THREAD

**Issue by nlf** [hapijs/contrib#17]
We don't list the companies that sponsor hapi or the site anywhere. I think we should have a place to list these companies and recognize their efforts.

For general sponsorship (i.e. companies that have developers who contribute a large portion of time to hapi) I would propose a special section in the `Community` page on the site, something to set them apart and bring attention to them.

For the site, maybe a small notice in the footer or sidebar?

The bigger question becomes, how do we determine what companies get listed where? Does anyone else have any thoughts?

**Comment by arb** [comment]
Who would be on the list of "general sponsorship"? Walmart and &yet? I didn't realize there were many others beyond that? I do like that idea though. It gives people confidence when they see know entities interested in an open source framework.

**Comment by nlf** [comment]
As of right now, that I'm aware of it would be Walmart (duh), &yet (for the site), and Digital Ocean (for the site's hosting)

**Comment by hueniverse** [comment]
I think we should set a threshold and let companies explain in a few words how they pass that. It should be set in monthly hours for people and $ amount for services.

**Comment by hueniverse** [comment]
This should be resolved by the new policy.
