### ISSUE TITLE
Create a jscs file that can help people follow the style guide

### ISSUE THREAD

**Issue by ulrikstrid** [hapijs/contrib#18]
We pretty much try to follow this style guide at my workplace and I'm about to create it for work, would the hapijs org be interested in that file when I'm done?

**Comment by Marsup** [comment]
We have already picked ESLint (see hapijs/discuss#22). It's lacking custom rules to fully cover the style guide but I think it can be achieved completely with that single tool. Lab already contains the defaults we intend to enforce across all hapijs projects.

**Comment by geek** [comment]
@ulrikaugustsson please share your jscs config.  With eslint we can get somewhat close to matching the style guide, but there are still parts missing.

**Comment by Marsup** [comment]
@geek why not add new ESLint rules ?

**Comment by geek** [comment]
@Marsup that is the better solution, just haven't got around to it yet.  I am happy if anyone else wants to contribute them :)

**Comment by ulrikaugustsson** [comment]
@geek I might just do the fleshed out ESLint then and share that

**Comment by mdarnall** [comment]
FYI I wrote up a few findings in #22. There looks to be several enhancements or custom rules to fully support the styleguides "spaces" and "newlines" conventions with eslint.

**Comment by jamesdixon** [comment]
@ulrikaugustsson did you ever end up creating a JSCS file based on the style guide? I setup Eslint with the Hapi rules, but I'm converting an older project and having to fix everything manually is terrible. I tried `eslint --fix`, but it's not doing a great job. `jscs --fix` seems to really nail fixing.

**Comment by ulrikaugustsson** [comment]
@jamesdixon Nope, sorry I quit before I finished it and have now changed work place so it's not relevant for me any more.
