### ISSUE TITLE
Mentorship program

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#19]
@nvcexploder: What's the status of the program? How many people are paired? Do we know if they are working together? How many people waiting to be paired (either side)? Do we need to add more people to help facilitate the program?

**Comment by nvcexploder** [comment]
Adding more mentors would always be helpful. I've started reaching out to
some mentors to take on more folks but haven't been assigning them yet.

**Comment by hueniverse** [comment]
That didn't actually answer any of my questions... :-)
