### ISSUE TITLE
Node 0.12

### ISSUE THREAD

**Issue by Marsup** [hapijs/contrib#20]
Now that node 0.12 is (finally) released, what's our plan for supporting it ?

I've enabled it on the projects I maintain, no sign of trouble in CI so far, but they don't rely on node core features that much.

**Comment by devinivy** [comment]
@Marsup was this issue stale or is 0.12 supported in full?

**Comment by Marsup** [comment]
I closed this one because it has already been answered in https://github.com/hapijs/discuss/issues/85.
You should know that 0.12 seems to have memory leaks though, several people running the exact same code see memory increase until the OS decides to kill the process. AFAIK we can't do anything about it.
