### ISSUE TITLE
Help facilitate the mentors program

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#21]
We got a great start with the fantastic work @nvcexploder put in but we need more help from people to facilitate the program, support the mentors, recruit more mentors, and use the program to help increase diversity.

If you are good at organizing and would like to help the hapi.js community in a non-technical role, this is a great role (you can always help with code!). I would like to add 2-3 new people to work on the program.

If interested, please reply here or to eran@hammer.io. Same if you have any questions.

**Comment by fhemberger** [comment]
What would be tasks you need help with? Not sure what a mentor program facilitator's job is, exactly …

**Comment by AdriVanHoudt** [comment]
More info [here](http://hapijs.com/help) but I would also like to know what the specifics are.

**Comment by nvcexploder** [comment]
Mostly what I've done is reach out to folks who want to be a mentor or a
mentee and match folks based on what mentors want to mentor, and what
mentees want to learn. The main focus is on encouragement on all sides -
providing help to those who need it in a friendly, encouraging way.

**Comment by AdriVanHoudt** [comment]
Tbh I watch interesting Hapi repos and I join in when I can and I'm on the Gitter whenever I can. So in a way I consider the whole community my mentor :D
What is the added value of being assigned a mentor or being a mentee?

**Comment by nvcexploder** [comment]
Some folks aren't comfortable doing that. The goal is to give as many
people as possible a gateway into learning the libraries and contributing
to the project and open source in general.

**Comment by AdriVanHoudt** [comment]
Oh ok so I could sign up as a mentee and do the same but have a specific person to talk to with more complex/all round problems? Can I ask a mentor to review plugin I write or is that not what is for?

**Comment by nvcexploder** [comment]
Sure!

**Comment by AdriVanHoudt** [comment]
I'll sign up to be a mentee then :D I know this issue is for mentors but I don't feel like I know enough of Hapi yet to be that ^^

**Comment by AdriVanHoudt** [comment]
Applied :D the link to the code of conduct is broken in form though.

**Comment by nvcexploder** [comment]
Dag - thanks for the heads up.

Also - it may take a bit to get you matched, which is the reason we've
posted this issue. :)

**Comment by AdriVanHoudt** [comment]
No problem I'll stay public community mentee for now

**Comment by nvcexploder** [comment]
Thanks! :D

**Comment by locnguyen** [comment]
I sent Eran an email but figured I'll drop a note here too. I'm interested in supporting the program. I think we just need to know what we can do next.

**Comment by nvcexploder** [comment]
I think Eran will forward those to me, and I can onboard you into how it
works. Sound good?

**Comment by jancervinka** [comment]
I'd be happy to help. I've sent an e-mail to Eran. I have also applied to be a mentee few weeks ago so hopefully this is not a problem. (I haven't heard back yet but I guess that's the point of this issue)

**Comment by jedireza** [comment]
I've learned so much since I started using hapi and it's extended universe. Sign me up.

**Comment by hueniverse** [comment]
I would like to see more active facilitation beyond just collecting the forms and matching folks. For example, it would be great to survey people every month and see how they are doing, if the program is adding value to them, or how it can be improved. I think a monthly virtual meeting of the mentors would be helpful to support each other (maybe a private channel to discuss things on Slack?).

Ben has done a great job setting this up but due to time restriction, was unable to get to the on-going facilitation part. We're looking for a few people who want to help with that and lead the effort, making sure it continues to add value and help people.

Leading this effort does not require being an expert on hapi because the role is purely community management, not engineering.

We got a few people who offered to help (but we can use more). The next step will be to setup a virtual meeting to discuss ideas and get people assigned action items.

**Comment by nvcexploder** [comment]
Eran if you can get me the people, I can set something up next week.

**Comment by hueniverse** [comment]
Done.
