### ISSUE TITLE
repository contribution expectations

### ISSUE THREAD

**Issue by csrl** [hapijs/contrib#22]
Hi,

I'd like to open discussion on etiquette and roles for community contributors (lead maintainers) contributing to each others repositories.

For reference: https://github.com/hapijs/contrib/blob/master/Governance.md#lead-maintainers 

It states the lead maintainer has final say over the repository that they lead, and I'm wondering what the practical implications of that should be, as we each have full read/write/admin access to the other's repos.

As an example that prompted me to bring this up at this time is that I was the recipient of a helpful direct contribution on the master branch of the 'glue' repo that I maintain.  To be clear, I have no issue with this specific contribution, and I appreciate the update from cjihrig.  But the event brought this topic back to my mind which I've previously considered from the opposite end - should I create a pull request and wait for the lead maintainer to merge it, or just push/merge the commits directly to the master branch of our community repositories myself?

There are the obvious cases - you don't go rewrite someone else's project.  But I'd like to contribute more to various repos, but opening a pull request and discussing something that is seemingly a minor/trivial update has too much overhead at times when I'm just trying to get things done.

Can we generate some guidelines that encourages contributions, reduces surprises and helps each other out?  Thoughts?

Chris

**Comment by hueniverse** [comment]
For projects I maintain, I expect others to follow these rules:
- Never merge PRs that change any dependencies or lib code
- Automatically merge trivial changes like adding examples, fixing documentation, or adding tests
- Avoid messing with milestones on issues
