### ISSUE TITLE
Standards on CI across projects

### ISSUE THREAD

**Issue by Marsup** [hapijs/contrib#28]
Hi all,

I've been refining [my travis CI build configuration](https://github.com/hapijs/joi/blob/master/.travis.yml) on joi for quite some time now, I think it's stable now.

I was wondering if it would be worth having the same setup across all our projects or if it really is up to the maintainer.

Builds seem to happen sooner and take less time than before, and auto-publishing packages from travis without the local artifacts I might have has been a great experience for me so far.

Thoughts ?

**Comment by arb** [comment]
What does this get us? The list of node versions is simple and easy to mentally parse. It's not instantly obviously what some of those settings are for.

**Comment by Marsup** [comment]
It's using cache and containers to speedup (a lot) the bootstrap of the tests, for the deployment I think it's pretty obvious.

**Comment by patrickkettner** [comment]
[`sudo: false`](http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure)

This explicitly sends the project to a container based system, which spins up substantially faster than the non container based systems.

[`deploy npm`](http://docs.travis-ci.com/user/deployment/npm/)  is pretty obvious. only thing to know is it pushes automatically when you tag if the [following are true](https://github.com/hapijs/joi/blob/a7d94d671f8c01d4d0c6e0d1d0337b9488037f43/.travis.yml#L21-L24)

`cache` is self evident, however I was under the impression this was only the case for private pro repos - is that not the case, @arb?

**Comment by Marsup** [comment]
I had to do the explicit npm update so it's here trust me, failed a few builds because of that :)

**Comment by patrickkettner** [comment]
sweet! great to know

**Comment by AdriVanHoudt** [comment]
So everything but deploy I can use on any repo and it will speed things up (given I don't need sudo ofc)
If those settings don't impact anything I see no reason to use them. The auto deploy might be less desirable since you are dealing with a fragile system. I don't really mind it for anything but hapi core itself

**Comment by hueniverse** [comment]
I'm all for consistency. Applying this change to all our modules would be a great beginners task. @Marsup Can you post a new issue with the instructions and I'll promote it?

**Comment by AdriVanHoudt** [comment]
If you have them today, I was gonna doe some PR's anyway so I could easily
add this (day just started here)

**Comment by Marsup** [comment]
Done, think we can close this one.
