### ISSUE TITLE
Maintainer SLA

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#29]
I would like us to get closer as a team to some basic SLA:
- Issues
  - labelled within 3 days
  - assigned, closed, or labeled with `help wanted` or `new contributor` within 1 week
- Pull requests
  - commented on within 3 days
  - merged, closed, or changes requested within 1 week

Anything else?

**Comment by AdriVanHoudt** [comment]
LGTM

**Comment by Marsup** [comment]
This is probably a best-effort thing since it's done on free time, which we might not have sometimes.

> merged, closed, or changes requested within 1 week

I'm often holding off some PRs to find time to make a proper decision, that won't go well for me.

**Comment by AdriVanHoudt** [comment]
well that falls under changes requested not? maybe add in a 'discussion started within 1 week' thing

**Comment by Marsup** [comment]
Not necessarily, sometimes I need to think whether I actually want it or not.

**Comment by AdriVanHoudt** [comment]
would 'discussion started' work for you or like issues 'labeled with...'?

**Comment by hueniverse** [comment]
@Marsup feel free to suggest changes to this. Also, this is what we should strive for, not a hard requirement. The goal is to set standards so that if someone fails consistently we can use that as the foundation of asking them to either improve or consider giving it to someone else.

A simple solution could be to just comment and set the right expectations as an exception handling for the SLA.
