### ISSUE TITLE
Repo style cleanup

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#31]
We need to apply this to all hapijs modules:
- Remove Makefile and switch to using npm scripts (see hapi package.json)
- Remove root index.js (point package.json to lib/index.js)
- Replace package.json licenses array with single license key and `"BSD-3-Clause"` value
- Update code style to stop putting functions on single line (new lab will error on that lint warning)

If you are looking for ways to help, submitting pull requests to the various modules would be great.

**Comment by guahanweb** [comment]
@hueniverse, is there a current list that shows the outstanding modules still needing cleanup?

**Comment by hueniverse** [comment]
@guahanweb no list. Just go through them and see which have stale issues or PRs, as well as outdated dependencies and non-compliant support files (travis, etc.).

**Comment by cjihrig** [comment]
Or make a dashboard with that information if you're feeling particularly spunky.
