### ISSUE TITLE
Form a Code of Conduct committee

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#36]
The committee will be responsible for maintaining and administrating the Code of Conduct and set the rules under which it will operate. The committee will have a lead which will be elected by the committee for a set period of time (an exception to the governance rules).

Please reply if you would like to join the committee.

**Comment by nlf** [comment]
Ooo, I want in please

**Comment by mark-bradshaw** [comment]
I'll volunteer I guess.

**Comment by hueniverse** [comment]
I am trying to avoid forming a committee for hapi and opt into one provided by the new node foundation so I am more inclined to help over there and get one going. Hence this is a bit on hold.

**Comment by mark-bradshaw** [comment]
Ok.  If it doesn't work out ping me.

**Comment by TheAlphaNerd** [comment]
I should be at the summit on Thursday. I would be more than happy to bring up node projects falling under the node committee. Specifically how the committee can come up with a cOc and best practices that can be adopted by the community.
