### ISSUE TITLE
Header graphic

### ISSUE THREAD

**Issue by mark-bradshaw** [hapijs/contrib#37]
Some of the hapi ecosystem packages have a distinctive graphic up top with the funky image and font.  Where are those coming from?

**Comment by hueniverse** [comment]
Walmart paid an artist to create those. We stopped doing it after the first 10 or so and none since.

**Comment by mark-bradshaw** [comment]
Ok. Didn't want to get left out. :)

**Comment by devinivy** [comment]
We created some art for [bedwetter](https://github.com/devinivy/bedwetter) and [dogwater](https://github.com/devinivy/dogwater).  If you have a plugin, it's worth reaching out!  I can't promise availability, but I do know a guy who quite likes to make Ren and Stimpy themed artwork :)
