### ISSUE TITLE
Editor configuration and style guidelines

### ISSUE THREAD

**Issue by jagoda** [hapijs/contrib#38]
While lab provides great enforcement around the hapi style guidelines, I find myself constantly needing to reconfigure my editor as I move between hapi projects and other open source projects. The main culprit is tabs vs. spaces for indentation. On other projects I have used [EditorConfig](http://editorconfig.org/) to help alleviate this issue. Adding an `.editorconfig` file with something like the following could make it easier and more convenient to adhere to the hapi style guidelines (if a developer uses an editor with EditorConfig support):

```
root = true

[*]
end_of_line = lf
insert_final_newline = true
indent_style = space
indent_size = 4
trim_trailing_whitespace = true

[*.{json,yml}]
indent_size = 2
```

I'm open to other suggestions on how to manage this issue as well.

**Comment by jagoda** [comment]
Anybody? I'm inclined to close this if I'm the only person who cares.

**Comment by AdriVanHoudt** [comment]
I don't personally use editorConfig, my IDE changes spaces/tabs on it's own, but I can see the benefit

**Comment by devinivy** [comment]
I agree that it could be useful during development, though I'm in the same boat as @AdriVanHoudt– my IDE detects this on its own.  Are there other configurations similar to .editorconfig?  I'd be a little wary of adding a config file if it means we ought to add three more configurations in the future to cater to everyone's development flow.  But if .editorconfig is a de facto standard, maybe this would be a good idea!

**Comment by jagoda** [comment]
Thanks for the feedback! I agree that we should be sensitive to creating too many configuration files. Out of curiosity, what IDEs are you using that is handling this automatically? If I'm the only one dealing with this because everybody else is using smarter IDEs then perhaps it makes more sense for me to consider a different editor.

**Comment by AdriVanHoudt** [comment]
I use Brackets with a plugin that does the detection. Then a plugin that does re-indentation and in the process removes trailing whitespaces. The newline at eof is an error eslint gives me so that is still something manual but not really a burden so.

**Comment by devinivy** [comment]
I use Komodo Edit.  It's sensitive to the basic style of the file you're working in (mostly just spacing), if it can detect it.

**Comment by mark-bradshaw** [comment]
I use editorconfig in my projects, usually.  I find it useful in keeping track of particular project needs, and I think it is something of a defacto standard.  I'm in favor of using it.

**Comment by Marsup** [comment]
Also in favor, but I think our ESLint rules already check that mostly, that comes a bit late (test phase).

**Comment by arb** [comment]
I vote no on this. It's just another thing to maintain that every repo would need a copy of. Lab uses the specialized rule sets and every repo has CI properly set up. I don't really see a benefit.

**Comment by devinivy** [comment]
Maybe we could simply provide an .editorconfig here in contrib or in the lab repo (versioned alongside the lints), and invite developers to pull it into their projects during development.

**Comment by mark-bradshaw** [comment]
Yeah, i was thinking something like that.  Since we seem to be putting a
lot of our eggs in the lab basket, why not put the editor config file
there.

**Comment by jagoda** [comment]
So I think what I'm hearing is more or less "Good idea in general, but not useful enough to enough people to warrant tracking/requiring yet another config file." More specifically, it sounds like @devinivy and @mark-bradshaw are suggesting recommending it as an option for developers and publishing examples, but not including the config file in the repos. I believe that this approach would address both my concerns and @arb's. That sound right to everyone?

**Comment by mark-bradshaw** [comment]
Sounds fine to me.  Thanks for following up.

**Comment by wswoodruff** [comment]
Has there been any hapijs official `.editorconfig` created yet?

**Comment by Marsup** [comment]
Not that I know of, I put one in lout as an experiment but never follow up here.

**Comment by Marsup** [comment]
@wswoodruff just added https://github.com/hapijs/joi/commit/cc53881b10a3017281442ab6df3fb75c1fe35081 which I think should satisfy most of our projects, not only on the editorconfig.

**Comment by wswoodruff** [comment]
I think that looks 👌 👍
