### ISSUE TITLE
Code Reviews

### ISSUE THREAD

**Issue by mark-bradshaw** [hapijs/contrib#39]
I'm looking for other contributors who have a bit of free time here and there, and would be open to getting pulled in for code reviews.  If you fit the bill, drop a line here please.

**Comment by devinivy** [comment]
I'm open to performing code reviews.  But right now I have a couple mrhorse projects on the docket that will require code review, and of course I oughtn't code review myself :P.

**Comment by mark-bradshaw** [comment]
No, actually I'm thinking about the [Accept module](https://github.com/hapijs/accept), which I also maintain.  I'm working on some updates there that need code review, but I don't want to lean on Eran to do all the reviews so I wanted to connect to one or more other Hapi contribs who would have the time to look over PRs and tell me what I've screwed up.  :)

I saw that you started working on Topo.  Are you going to pick that module up at lead maintainer?

**Comment by devinivy** [comment]
Oh, got it!  Sadly, I don't think I would be much use code reviewing for Accept at the moment.  Maybe in the future, though.  I am hoping to pick-up topo!

**Comment by mark-bradshaw** [comment]
Good luck with topo.  I was actually going to suggest to you that you pick up a module, so I'm glad that you're already thinking that way.

**Comment by nlf** [comment]
I'm generally available for code review. Just assign pull requests to me or mention me in them and I'll see them.

**Comment by mark-bradshaw** [comment]
Thanks Nathan.
