### ISSUE TITLE
JsPerf being rebuilt w/ Hapi

### ISSUE THREAD

**Issue by mark-bradshaw** [hapijs/contrib#40]
This might be old news, but jsPerf (which is currently down - https://github.com/jsperf/jsperf.com/issues/18#issuecomment-113569132) is being rebuilt using Hapi.

https://github.com/jsperf/jsperf.com is the repo for the rebuild.

**Comment by Marsup** [comment]
That's nice, I can also see they're going with iojs, that would be the 1st high traffic site with io+hapi (that I know of), this is good for battle testing on more recent VMs.
