### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gergoerdosi** [hapijs/contrib#41]
What's the license of these documents?

**Comment by hueniverse** [comment]
In this repo? public domain.

**Comment by gergoerdosi** [comment]
Yes, I meant this repository. Would it be possible to add a LICENSE file? GitHub says:

> Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

https://help.github.com/articles/open-source-licensing/

At the moment I'm doing a derivative work (copying some parts) to create our own guides.

**Comment by hueniverse** [comment]
I'll take a PR. Easiest to use the default hapi BSD license file.
