### ISSUE TITLE
"Enforcing new on constructor" style prevents inheritance?

### ISSUE THREAD

**Issue by harrytruong** [hapijs/contrib#43]
> #### Enforcing new on Constructor
> - Use this.constructor === to check if a constructor function was called with new
> 
> ```
> // Right
> Hoek.assert(this.constructor === Server, 'Server must be instantiated using new');
> 
> // Wrong
> Hoek.assert(this instanceof Server, 'Server must be instantiated using new');
> ```

https://github.com/hapijs/contrib/blob/master/Style.md#enforcing-new-on-constructor

I'm sorry if this is a dumb question, but I couldn't find documentation on why this style exists. By asserting `this.constructor === Server`, prototypical inheritance breaks. Was this intentional?

``` js
// helper to enforce new on constructor
function assertUseNew(ctx, constructor) {
    // breaks for example below
    if (ctx.constructor !== constructor) throw 'Use new!';

    // works for example below
    // if (!(ctx instanceof constructor)) throw 'Use new!';
}

// this inheritance helper comes from babel (6to5)
function inherits(subClass, superClass) {
    subClass.prototype = Object.create(
        superClass.prototype,
        { constructor: {
            value: subClass,
            enumerable: false,
            writable: true,
            configurable: true
        } }
    );

    Object.setPrototypeOf(subClass, superClass);
}


// base class of "Foo"
var Foo = function (key) {
    assertUseNew(this, Foo);
    this.key = key;
}

// child class of "Bar" (style of inheritance comes from babel/6to5)
var Bar = (function (_Foo) {
    inherits(Bar, _Foo);
    function Bar(key) {
        Object.getPrototypeOf(Bar.prototype).constructor.call(this, key);
        assertUseNew(this, Bar);
    }
    return Bar;
})(Foo);


var foo = new Foo(true);
console.log('Successful foo: ' + foo.key);
try {
    var foo = Foo(true);
} catch(e) {
    console.log('Successful Foo non-new error.');
}

var bar = new Bar(true); // <========================== !!!
console.log('Successful bar: ' + bar.key);
try {
    var bar = Bar(true);
} catch(e) {
    console.log('Successful Bar non-new error.');
}

console.log('Successful inheritance: ' + (bar instanceof Foo));
```

When `ctx.constructor !== constructor` is used, the `var bar = new Bar(true);` line breaks. Uncomment `!(ctx instanceof constructor)` to confirm it works just fine.

What was the rationale for `ctx.constructor !== constructor`?

**Comment by hueniverse** [comment]
This is done to protect users of the public API from forgetting to call `new`. There are two typical ways of doing this, one is passive which is what we do (just prevent it) and active (call `new` in the constructor).

This is done only in publicly exposed APIs. Internal prototypes don't have that. You should have no reason to use prototypical inheritance from hapi object API interfaces.

**Comment by harrytruong** [comment]
Thanks for the very quick response! 

> This is done to protect users of the public API from forgetting to call new. There are two typical ways of doing this, one is passive which is what we do (just prevent it) and active (call `new` in the constructor).

I agree with the passive method (just preventing it), but the check logic is what I'm surprised by: `this.constructor === Constructor` instead of `this instanceof Constructor`. 

Just to be clear, I'm not advocating for active protection.

> You should have no reason to use prototypical inheritance from hapi object API interfaces.

Haha, I agree. I'm not using hapi's `Server` in the intended way, but I don't think it hurts to reuse and extend hapi's objects for other projects? The current implementation prevents inheritance, while the alternative would allow for it (and would still passively protect against missing `new`).

P.S. I'm sorry if this discussion is irrelevant, but I figured at least documenting the behavior on an issue ticket would help anyone else who comes down this path in the future.

**Comment by harrytruong** [comment]
I traced the `this.constructor === Constructor` choice back to @thegoleffect, [way back in 2012](https://github.com/hapijs/hapi/blob/eb29245f2d4935d8b3aa503a2cbc5a64a07c7aaf/lib/server.js#L45). Maybe he can explain why it was used instead of `this instanceof Constructor`?

**Comment by hueniverse** [comment]
What's your use case here?

**Comment by harrytruong** [comment]
Just repeating [myself here](https://github.com/hapijs/hapi/issues/2663#issuecomment-125010914) for clarity: 

> I have no real reason. I was playing around with reusing Hapi's components in a side project. When I extended from Server to test something, I saw the implementation, and was just curious about the rationale behind it.

Also pinging @geek here because he added [this style rule back in 2012](https://github.com/hapijs/hapi/commit/f44f1fc4ffca4c8c3a7fe0de90bb55c14544f997). Just want to be 100% sure I'm not misunderstanding the reason for `this.constructor === Server`. (TBH, the fact that it explicitly says `// Wrong`, makes me very paranoid.)
