### ISSUE TITLE
3rd party integration tests and secrets

### ISSUE THREAD

**Issue by ldesplat** [hapijs/contrib#45]
Hi,

I am maintaining the bell module and we have built in providers which integrate with 3rd party services. Most of the services, have online versions that we can test against.

It would be very useful if the CI could actually run some live tests to ensure that PRs do not break anything with the 3rd parties or detect if 3rd parties have changed their APIs. Right now, I attempt to do it myself but it's manual work...

Practically this would mean the following:
- Add a folder for "integration" tests that are only run in CI
- Configure travis to have some predefined clientId and clientSecret for each service. This can be encrypted (http://docs.travis-ci.com/user/encryption-keys/)

My questions or concerns are the following:
- Would it be possible to create "Hapi" credentials? (ie. for facebook, google, ...)
- 3rd Party PRs would not be able to run those tests unfortunately (someone could easily leak the secrets otherwize).

Any thoughts?

**Comment by hueniverse** [comment]
First step is to automate testing for yourself. If you can use some Travis features to then automate it without leaking the credentials, go for it.

**Comment by DavidTPate** [comment]
You could use [Encrypted Variables[(http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables) on Travis. The only concern that I can think of would be that anyone with access to the repository would be able to get the decrypted keys (likely through modification of the code to log the keys).

**Comment by AdriVanHoudt** [comment]
that turned out to be a not so cool option https://github.com/hapijs/contrib/issues/30 :P

**Comment by DavidTPate** [comment]
Exactly, I searched through hapijs/discuss and hapijs/joi for that issue, but didn't think to search here for it. Thanks @AdriVanHoudt

**Comment by AdriVanHoudt** [comment]
yeah I don't see the value of having discuss and contrib :P but glad I could help ^^

**Comment by ldesplat** [comment]
It appears having those types of tests executed by a CI server will be a no go.

When I create these integration tests, I'll make a public repository with them. I can revisit how to integrate it a bit better then.

Thank you.
