### ISSUE TITLE
API.md

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#47]
I would like to suggest a new common style. Every module should have an API.md file instead of keeping the API docs in the README.md. This will allow us to automatically generate pretty API docs for all the modules and plugins on the hapijs.com site. It needs to follow the exact same structure rules of the hapi/API.md file (which would be great if someone documented).

**Comment by mark-bradshaw** [comment]
Seems reasonable to me.

**Comment by nlf** [comment]
further detailed in #49
