### ISSUE TITLE
Wanna help?

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#48]
There are plenty of ways to contribute to the hapi.js project:
- [Become a module lead maintainer](https://github.com/hapijs/contrib/issues/33) - some of the modules available require very little effort.
- [Help maintain the hapijs.com site](https://github.com/hapijs/hapijs.com/issues) - there are a lot of improvements needed and the skills required to perform some of these tasks are perfect for new contributors.

**Comment by ArmenAvetisyan** [comment]
Hi, @hueniverse!

**I get an error** going through a quick instruction of the first deployment.
I install all dependencies. But when I run `npm start` it says:

![hapi_installation_error](https://cloud.githubusercontent.com/assets/17157264/21750480/c4f16052-d5c4-11e6-92af-3d2ee15a6815.PNG)

How can I handle this error?
I've already updated npm. No results.

Thanks!

**Comment by arb** [comment]
Whatever port you're trying to use, something is already using it.

Additionally, this issue is asking for new contributors to the hapi ecosystem. If you have a question, please open a *new* issue in the discus GItHub repo.

**Comment by ArmenAvetisyan** [comment]
Thank you @arb!
I'll open an issue.

**Comment by saqibnaveed** [comment]
Hello. I am a junior developer and I'd like to help

**Comment by AdriVanHoudt** [comment]
@saqibnaveed the best way to start is to look at the open issues and chime in to see what needs to be done

**Comment by saqibnaveed** [comment]
@AdriVanHoudt Okay thanks :+1:
