### ISSUE TITLE
Module documentation changes

### ISSUE THREAD

**Issue by nlf** [hapijs/contrib#49]
In support of hapijs/hapijs.com#227 we need to reorganize documentation in the plugins a little bit. Each module should have two markdown files in the root of their repositories with the content described below:

README.md
- name of module
- build status badges (travis-ci, etc)
- name of lead maintainer
- sponsorship information, if applicable
- short description of the plugin
- short example of a common use case (with code)
- link to API.md

API.md
- API documentation, in a format as similar to the API.md in hapijs/hapi as possible

this is another documentation change that would be a great place for new contributors to help out where possible.

**Comment by devinivy** [comment]
Does this apply to non-plugin modules?

**Comment by nlf** [comment]
it would probably be a good idea for all modules in the hapijs organization to follow this pattern.. i'll change the text

**Comment by devinivy** [comment]
Something I've always been a little hazy on– does this type of documentation change warrant a patch version?

**Comment by mark-bradshaw** [comment]
I would say no if functionality isn't changing.

**Comment by Marsup** [comment]
@nlf what are the points that are important to follow for the API.md ? I did it for Joi but I'm not sure what to look for to help the site build the docs.

**Comment by nlf** [comment]
the main concern is making sure that the table of contents exists in the same format as hapi's API docs (with the title at the top, followed by the toc). i'm sure there will probably be some tweaks to make along the way. i'm working with our designer, karolina, on prepping the site to add these docs
