### ISSUE TITLE
Must internals be declared if it's not used?

### ISSUE THREAD

**Issue by danielb2** [hapijs/contrib#50]
Currently the style guide says:

```
internals - must be declared as an object at the top of each module immediate following the require section
```

However, it seems bad practice to declare unused variables.  I think the spirit of this is simply saying that only `export` and `internals` are allowed global variables, and this section simply specifies where it should be declared.

Thoughts?

**Comment by devinivy** [comment]
What you're saying sounds right to me.

**Comment by mark-bradshaw** [comment]
That's the way I think of it.

**Comment by hueniverse** [comment]
This came up before. You don't have to declare it if you are not using it. I usually do to be consistent.
