### ISSUE TITLE
Assertion library in tests

### ISSUE THREAD

**Issue by gergoerdosi** [hapijs/contrib#51]
I noticed that test scripts are defined with the `-a code` option in the hapijs repositories:

```
"test": "lab -a code -t 100 -L",
```

However this adds no value, because `Code` is used directly in test files:

```js
var Code = require('code');
var expect = Code.expect;
```

So I'm curious, is there a reason why `-a code` is used, but `var expect = Lab.assertions.expect;` is not?

**Comment by hueniverse** [comment]
It is used to turn on lab+code integration features (e.g. make sure you didn't forget `()` at the end of expect assertions).

**Comment by gergoerdosi** [comment]
Can you please give me a hint where I can find the code for that? What I can see is that `-a code` just requires the assertion library and makes it available under `Lib.assertions`.

https://github.com/hapijs/lab/blob/master/lib/cli.js#L299-L302

So if `var expect = Code.expect;` is used in test files, then `-a code` seems to be unnecessary.

**Comment by gergoerdosi** [comment]
Never mind, I think I found it:

https://github.com/hapijs/lab/blob/master/lib/runner.js#L90-L100

Thanks for the help!
