### ISSUE TITLE
hapi-lts and peer dependencies

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#52]
Today we published a new LTS version of hapi: https://github.com/hapijs/hapi/issues/2765.

The reason for a separate module is that npm is painful to use for two active branches with latest tag management. However, this will prevent **hapi-lts** users to install plugins once we publish new versions of the LTS branch.

Options:
- require npm v3 with the warning disabled.
- publish lts versions of current modules (not ideal).
- other?

If someone has a good way to managing npm parallel releases I'm open to that but my experience has been pretty bad in the past with hapi v8.

**Comment by nlf** [comment]
in my mind, the biggest question is are we going to be encouraging plugin and module authors to do the same transition as hapi is doing (with a node4 version and a node 0.10 version). if so, then lts versions of everything is probably the way to go even though it's ugly.

another way to do it would be with an lts tag in npm rather than a different package entirely. then users would `npm i hapi@lts good@lts` etc

**Comment by hueniverse** [comment]
How would that work in package.json?

**Comment by nlf** [comment]
you'd have a master branch with a version that's ahead of the lts branch, when publishing the lts branch you'd have to remember to pass the `--tag` argument to npm which sucks, but at least npm tags can be changed if you make a mistake

**Comment by cjihrig** [comment]
Will there ever be more than one active LTS? I know Node core is planning to have an overlap period where there are two LTS releases at the same time.

**Comment by nlf** [comment]
that sounds like a pain to manage, IMO especially since we never officially supported node 0.12 anyway, we shouldn't ever have more than one lts

**Comment by cjihrig** [comment]
I'm not necessarily advocating for it, just curious. I believe the motivation is to give people time to upgrade during the overlap period. 0.12 isn't really relevant though, as the same problem would come up later down the line with v4, v6, etc.

I personally think one LTS is enough.

**Comment by hueniverse** [comment]
One LTS.

**Comment by nlf** [comment]
I agree, once we reach the end of life of the current LTS it's entirely possible/probable we won't have a new one again

**Comment by hueniverse** [comment]
I think npm 3 is the way to go. Should be out any minute.
