### ISSUE TITLE
Coveralls.io

### ISSUE THREAD

**Issue by skeggse** [hapijs/contrib#53]
I'm the lead maintainer over at [hapijs/isemail](https://github.com/hapijs/isemail).

To my knowledge, we're currently using Travis CI as our only integration point. I'd like to also use [coveralls.io](https://coveralls.io) for automated code coverage. It basically just gives the tests an API to hit from Travis CI that will update coverage analytics and a badge. This integration requires granting coveralls organization access on GitHub, and I'd like to give any interested parties an opportunity to shoot down or approve this idea.

I'm not married to coveralls, if you have a recommendation for another code coverage service, I'm all ears. I realize that this kind of integration isn't necessarily useful for all hapijs projects, but it's more significant for an email address validator than some other projects.

**Comment by nlf** [comment]
i'm not entirely sure about this. we already have the rule that projects require 100% code coverage, which is enforced by lab (which is run in travis). what does this gain us on top of that?

**Comment by skeggse** [comment]
For people who aren't familiar with the requirements of hapijs projects, it shows that testing is a vital part of the project. It doesn't provide much of anything beyond that.

**Comment by skeggse** [comment]
Email subscribers: I suppose to that end I could just note said requirement under the Travis build status badge in the readme.
