### ISSUE TITLE
Conflict: usage of hasOwnProperty check gives coverage issues

### ISSUE THREAD

**Issue by danielb2** [hapijs/contrib#56]
`Use for with arrays, for...in for objects (and always check hasOwnProperty())`
https://github.com/hapijs/contrib/blob/master/Style.md#for-loops

Using the advised `for...in` syntax is practically impossible while still following 100% coverage rules together with style guideline.  Causing a failing `if` check there is impossible when just declaring something as an object moments earlier.

In order to "follow" guidelines, we end up writing Object.keys(obj) instead and iterating over that result for the 100% coverage. However, that conflicts with the mandate to use `for...in`

So can this rule be revised so both 100% code coverage and style can be followed?

I suggest not requiring `hasOwnProperty` for locally defined objects. If a variable is declared earlier, (e.g. `internals.staticObj`), then it shouldn't be an issue.

**Comment by geek** [comment]
I don't think there is a mandate to use for...in, just that you should use it with objects:

```
Use for with arrays, for...in for objects
``

**Comment by danielb2** [comment]
But you can't use it with objects, and have 100% code coverage. You basically end up never ever using it at all. So I think the options are to either not using `for...in` or sometimes not having hasOwnProperty check.   not using `for...in` is probably the safer and more consistent way.

**Comment by geek** [comment]
Is the code coverage not possible because the condition is always true for the object you are checking?

**Comment by danielb2** [comment]
Yes

``` javascript
var obj = {};

for (var key in obj) {
    if (!obj.hasOwnProperty(obj)) {
        continue;
    }
    // do things
}
```

the continue isn't ever reached here.

**Comment by geek** [comment]
Sounds reasonable to do what you suggested, just not require the `hasOwnProperty` for conditions like you describe.  Maybe open a PR for the styleguide to make it more lenient.

**Comment by danielb2** [comment]
:+1:

**Comment by hueniverse** [comment]
I never use this style anymore. Always `Object.keys()` and simple for loop.
