### ISSUE TITLE
Thoughts on the next major lab version cutting node 0.10 support?

### ISSUE THREAD

**Issue by geek** [hapijs/contrib#60]
I want to get opinions from you all if I make the next major lab version only support node 4+.

This is in reference to a comment @Marsup raised: https://github.com/hapijs/lab/pull/471#issuecomment-151067801

**Comment by AdriVanHoudt** [comment]
:+1:

**Comment by nlf** [comment]
i think this question applies to most of our module ecosystem..

that said, personally i'm all for it.

**Comment by hueniverse** [comment]
Yep. Up the major and remove 0,10 support.

**Comment by AdriVanHoudt** [comment]
I hope this can fix the tests of https://github.com/hapijs/hoek/pull/165 being all weird
