### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by jamesdixon** [hapijs/contrib#61]
As I was sitting here wiring up some Joi validations in Hapi while listening to some sappy acoustic music, I was thinking: "wow, if I had to write all of this from scratch, I'd throw myself into oncoming traffic." That said, just wanted to give a shout-out to everyone who's contributed to the Hapi ecosystem, especially @hueniverse and the original core team; you've saved me a lot of time, money and headaches and that should be recognized. If my product ends up making any money one day, it'd be good to buy everyone a beer or preferably some really good whiskey.

Looking forward to getting more involved in the community.

James

**Comment by AdriVanHoudt** [comment]
Same here, if any of you is in Antwerp, Belgium, let me know ;)

**Comment by Marsup** [comment]
Much appreciated, thanks man :)

**Comment by devinivy** [comment]
:beers: Yes, thanks to the original core team and to all the newer folks for keeping it well-oiled.  Using hapi has been an incredibly pleasant experience– it has an exciting feature set and API that have been fun to watch grow and stabilize.  We have a handful of hapi converts over here in Portland, ME– reach out if you're nearby!  @jamesdixon see you in the github issues!
