### ISSUE TITLE
ES6 style: heads up

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#62]
I am going through all the hapijs modules hapi depends on and publishing new major versions with the new ES6 style applied. This will remove node 0.x support and will upgrade to lab 7 which comes with new linting rules. This has to be done in a specific order otherwise we will be publishing new modules forever. I will be doing it for all modules hapi depends on and will open issues on the rest once the core modules are done.

**Comment by devinivy** [comment]
Sounds good.  I hope you used topo to determine the order.

**Comment by mtharrison** [comment]
Happy to help with rolling out to other hapijs org modules if help is required.

**Comment by hueniverse** [comment]
I'm done with everything hapi depends on. Feel free to open issues on everything else poking people to do the same (or just PR).

**Comment by mtharrison** [comment]
Cool. I'll open some and leave maintainers some time to implement. If not, I'll PR them too.
