### ISSUE TITLE
New rule for errors in callbacks

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#65]
If a callback has a first argument called `e`, `err` or `error`, the function must use it, This will enforce handling errors. To bypass it, simply call it `ignore` or anything else that documents your intentions.

**Comment by cjihrig** [comment]
At first glance, this appears to be easily enforceable with linting - http://eslint.org/docs/rules/handle-callback-err

**Comment by skeggse** [comment]
I've also seen `ex` every now and then, so it might make sense to include that.

**Comment by hueniverse** [comment]
Cool!

**Comment by cjihrig** [comment]
This thread kind of died off. Should I enable the linting rule for this?

**Comment by johnbrett** [comment]
I'm +1 on this!

**Comment by hueniverse** [comment]
yes
