### ISSUE TITLE
New logo?

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#68]
I think it's time. We are no longer using the Ren & Stimpy theme so maybe refresh the logo with something cleaner and more up to date?

**Comment by nlf** [comment]
interesting. let me talk to someone i know :)

**Comment by AdriVanHoudt** [comment]
Just make sure I can get stickers ;)

**Comment by devinivy** [comment]
![](http://2.bp.blogspot.com/--oxYRVj9pLU/USHUDioWBNI/AAAAAAAAhhE/tNlt7n6wBJY/s1600/syklmrcjgif.gif)

**Comment by adityabakle** [comment]
same here :) sticker for me too

**Comment by geek** [comment]
We owe it to everyone to keep the logo fun loving.  

Should we keep the same orange color we have on the site (#f6941e)?  Do we fit the design into a hex?

**Comment by kepano** [comment]
We've enjoyed using hapi for lumi.com – let me know if we can contribute some stickers :)

**Comment by davepoon** [comment]
A minimalist logo could be a great option, which is easier to get people to remember.
A great use of minimalist logo could convey the message of simplicity and reliability from the hapi framework.
hapi could even define a new visual language, a brand redesign, not only the logo.
Meteor.js is an great example to see the success of the redesign, which increase publicity around the framework.
Please let me know if you need any of my design contribution ;)

**Comment by jhrobles** [comment]
![hapi](https://cloud.githubusercontent.com/assets/10146684/12462332/90b5cf9e-bf72-11e5-92ac-d3100d13c2cb.png)

How is this? I wasn't sure if you wanted to pull completely away from the helmet/Ren & Stimpy.

**Comment by hueniverse** [comment]
@jhrobles thanks! That's a great option. I'm sure people will have comments. I need to stare at it for a bit :-)

**Comment by AdriVanHoudt** [comment]
@jhrobles great job, personally I did like the detail of the current one, also it has more colors and the weird angle :P

**Comment by nlf** [comment]
I definitely like this simpler approach better than the old logo. I asked @jhrobles to come up with a few other non-helmet ideas too :)

**Comment by AdriVanHoudt** [comment]
I do like the helmet, and not against flat logos, I like the one from eslint a lot

**Comment by paulovieira** [comment]
Good work! I like it, but it's a bit too "clean", maybe... One thing I like in the current logo is the childish aspect.

Also, it immediately reminded me of the reddit logo. Anyone else too?

<img src="http://core0.staticworld.net/images/article/2012/11/reddit_log-100011890-large.jpg" width="250">

**Comment by dylan-cromwell-sociomantic** [comment]
@hueniverse from reading the thread I understood a logo has not yet been chosen. Thus, I let one of our Designers at Sociomantic know about this issue. They are very excited and whipping up a proposal logo for you now. I can't say precisely how long they need, maybe a couple of weeks?

**Comment by vctrfrnndz** [comment]
@hueniverse We use HapiJS in out projects at Auth0 and one of our team members told me you were looking for a logo. I tought I might have a go at it, this is my proposal:
![hapijs](https://cloud.githubusercontent.com/assets/3391028/13190154/3951252a-d73a-11e5-9d84-18550933ec13.png)

**Comment by hueniverse** [comment]
@vctrfrnndz nice! These are very cool. I am not sure keeping the helmet concept but going in another direction makes sense though. The existing helmet was from Ren and Stimpy Happy Happy Joy Joy song.

@dylan-cromwell-sociomantic would be cool to get more options, thanks!

**Comment by dylan-cromwell-sociomantic** [comment]
@vctrfrnndz yes those are very cool! Dig the calm, humble style and flat illustrative quality. Nice color schemes too!

@hueniverse yup will post the work from our Designer ASAP once it's ready. Thanks for the opportunity here!

Also, if you have anything specific you'd want me to pass along to the Designers, please let me know. They are very receptive to direction.

**Comment by zoe-1** [comment]
![hapilogodev2](https://cloud.githubusercontent.com/assets/1852507/13339581/d543449c-dbf7-11e5-8ed1-e7a1049bfbd2.png)

Got inspired and came up with this today.
It goes in a different direction than the helmet etc.

**Comment by zoe-1** [comment]
![hapilogopluginname2](https://cloud.githubusercontent.com/assets/1852507/13339610/194c893c-dbf8-11e5-912b-79899484c386.png)
Has space to brand hapijs plugins too.

**Comment by zoe-1** [comment]
![hapilogodevsideways2](https://cloud.githubusercontent.com/assets/1852507/13339646/3c10a44e-dbf8-11e5-8685-36c90f693adc.png)
Also came up with this one. 
It is for the "just shut up and use open source"  moments. :-)

**Comment by zoe-1** [comment]
![hapilogostandardpop](https://cloud.githubusercontent.com/assets/1852507/13368509/1189709a-dcb9-11e5-9501-f5b92ce75fa1.png)

Changed the size proportions between the H and the api.

**Comment by zoe-1** [comment]
![hapilogosmileslantpop](https://cloud.githubusercontent.com/assets/1852507/13368536/3da75d18-dcb9-11e5-9ab2-b69266eee555.png)
Playing with happy H concept.

**Comment by zoe-1** [comment]
![hapilogosmilestraightpop](https://cloud.githubusercontent.com/assets/1852507/13368553/6ac259e2-dcb9-11e5-80cc-c89a08f9d8ad.png)
Another happy H concept.

**Comment by nlf** [comment]
hmm.. i like the style of it, the only issue i take with any of these @zoe-1 is that we've already established that `hapi` is always all lowercase, so it seems weird to see the H capitalized

**Comment by zoe-1** [comment]
@nlf hmmm.... that is an issue. 
Will put more thought into it.
The capital H is more proportional so easier to design with.

**Comment by zoe-1** [comment]
lower case concepts below:
![hapilowercaseeyesboxes](https://cloud.githubusercontent.com/assets/1852507/13370591/65d42da4-dcda-11e5-9222-3b1a01d3c375.png)

**Comment by zoe-1** [comment]
![hapilowercaseeyesangle](https://cloud.githubusercontent.com/assets/1852507/13370599/940fd9c0-dcda-11e5-9315-37c313de9ea3.png)

eyes on angle

**Comment by zoe-1** [comment]
![hapilowercaseeyesstraight](https://cloud.githubusercontent.com/assets/1852507/13370600/aa368c4e-dcda-11e5-8c26-e8d9587cd3d6.png)
eyes straight ahead.

**Comment by zoe-1** [comment]
![hapilowercaseeyesboxesnosmile](https://cloud.githubusercontent.com/assets/1852507/13370606/c67b1a82-dcda-11e5-82c6-5f9d94596838.png)

**Comment by zoe-1** [comment]
I think lowercase looks better :-)
@nlf what do you think?

**Comment by arb** [comment]
I think https://github.com/hapijs/contrib/issues/68#issuecomment-189572206 is my favorite of your recent posts; FWIW.

**Comment by devinivy** [comment]
@vctrfrnndz https://github.com/hapijs/contrib/issues/68#issuecomment-186426073 looks _very_ nice!

I don't mind the helmet staying around, especially if it has a very different character (as in the logo referenced above).  What do we think of the all-caps in that logo?  The all-caps don't offend me, but we do typically stylize "hapi" to be entirely lowercase.

**Comment by AdriVanHoudt** [comment]
I also do like the helmet, and while cool ones by @zoe-1 and find them not to readable, could be me.

**Comment by danielb2** [comment]
:+1:  for jrohbles with https://github.com/hapijs/contrib/issues/68#issuecomment-173352864

Doesn't bring it too far from the original plot, and it's clean

**Comment by devinivy** [comment]
@vctrfrnndz mind if I play around with altering the type in your logos?

**Comment by zoe-1** [comment]
![hapilowercasesolid](https://cloud.githubusercontent.com/assets/1852507/13377431/22fab442-dda9-11e5-9a59-2209ec5cb719.png)

**Comment by zoe-1** [comment]
![hapilowercasesolidframework](https://cloud.githubusercontent.com/assets/1852507/13377438/80f32782-dda9-11e5-8896-47a1ca020dc4.png)

**Comment by zoe-1** [comment]
Previous two logos are an attempt at a clean and pure look.
No fuss no confusion.

**Comment by vctrfrnndz** [comment]
@devinivy Not at all, in fact I'll send over lowercase versions

**Comment by vctrfrnndz** [comment]
See these alternates, also tested out the concept on your website:

![logos](https://cloud.githubusercontent.com/assets/3391028/13380828/cb996a5e-de2a-11e5-8ebc-a384e038ae8b.png)

![website](https://cloud.githubusercontent.com/assets/3391028/13380830/cde2c7c4-de2a-11e5-81a8-de7b66afb433.png)

**Comment by jamesdixon** [comment]
@vctrfrnndz that looks mighty slick..well done!

**Comment by kepano** [comment]
@vctrfrnndz I like it! Can I make a minor suggestion? The logo should be facing right, it a subtle change but suggests "looking forward" rather than looking back.  

![cb996a5e-de2a-11e5-8ebc-a384e038ae8b](https://cloud.githubusercontent.com/assets/10565871/13381705/75a6cf50-de17-11e5-8893-4b61d814401a.png)

**Comment by AdriVanHoudt** [comment]
Oh wow I like the lowercasing!

**Comment by semateos** [comment]
@vctrfrnndz @kepano I like it - and, yeah right facing is a big deal, it generally means "good guy" and "progress" - think super mario.  Agree that the lowercase is better - a bit more friendly.  In the single-color outline versions the variation in line-weight is a little odd-feeling in places - particularly the interaction between the antenna and the outer helmet line - I might play with that a bit.  @vctrfrnndz would you post the vector file?  

I really like the full color version and I think it could be a lot of fun to see it animated.  For example, the helmet could have a visor that starts closed where and you can't see the face, it flips open to revel the face, the person nods or winks, and the antenna shifts up into position.  Or, the antenna shifts (like the helmet has turned on) and then the eye goes from sad looking to insanely happy looking.  Or something along those lines...  any motion graphics people out there?

Anyway, really nice work!

**Comment by vctrfrnndz** [comment]
@kepano That's a really good point, already flipped the logos.

@semateos Sure, here's an SVG, final vector file may need some more work, but its good enough for a concept.

[HapiJS.svg](https://github.com/hapijs/contrib/files/151156/HapiJS.svg.zip)

**Comment by woloski** [comment]
+1 to that logo. Looks beautiful. I want the sticker right now. Great job @vctrfrnndz

**Comment by hueniverse** [comment]
The problem with the logo from @vctrfrnndz is that while it is very well done,clean, and project the kind of professional image we want, it makes little sense. It took the helmet concept into a direction that just doesn't relate to the framework. The existing logo's helmet is from the happy happy joy joy episode of ren and stimpy. An astronaut helmet just doesn't have a thematic relation to this project.

It is a absolutely great logo. I just don't see how it fits this project.

**Comment by vctrfrnndz** [comment]
@hueniverse Totally understand, if I find time this week I will make another proposal.

Let me know if you or anybody else here have ideas or concepts for me to work off.

**Comment by devinivy** [comment]
Here are some core hapi-specific concepts that could have visual counterparts–

1. Plugins and composition of "server-partials"
2. Server extensions / the request lifecycle
3. Configuration over code

**Comment by AdriVanHoudt** [comment]
@devinivy add predictability to that

**Comment by zoe-1** [comment]
![hapifaceverticalbranding](https://cloud.githubusercontent.com/assets/1852507/13539728/28e7f6f0-e220-11e5-9500-7a7f5acb8c8a.png)

Configuration Centric hapi face.
radial knobs for eyes.
slider controller for mouth.
Plus, custom hapi name text.

**Comment by zoe-1** [comment]
![hapifacevertical](https://cloud.githubusercontent.com/assets/1852507/13539786/8c1063fc-e220-11e5-9c5b-50acc197a950.png)

Same as previous but with different font.

**Comment by zoe-1** [comment]
![hapifacenameright](https://cloud.githubusercontent.com/assets/1852507/13539811/a79fa13c-e220-11e5-8494-5a7c2d388bee.png)

hapi face to left of name. 
Positioned for branding at top left of page similar to github's octocat.

**Comment by zoe-1** [comment]
Above design attempts to use elements which communicate configuration
(radial dials & slider controllers) to create a happy face.
The image is to communicate: "use hapi to configure your api and you will be happy".   

Also was considering using an infinite loop to create a happy face (or something that feels happy)
with arrows on the loop to signify lifecycle and life etc.  But, only had time this week to come up with the above.

**Comment by dylan-cromwell-sociomantic** [comment]
Wow love to see all the activity here! Wanted to submit the first round of designs coming from our UK-based designer, Chelsea:

First Version 1

![hapijs-01](https://cloud.githubusercontent.com/assets/2911544/13649858/8c3a2e1a-e61e-11e5-81e5-8acd1e44d98e.png)

**Comment by dylan-cromwell-sociomantic** [comment]
And then version 1 alternates:

![hapijs-03](https://cloud.githubusercontent.com/assets/2911544/13649868/9a32eade-e61e-11e5-8b73-a241b6aa56b6.png)

**Comment by dylan-cromwell-sociomantic** [comment]
Next up version 2:

![hapijs-02](https://cloud.githubusercontent.com/assets/2911544/13649873/a261dbfc-e61e-11e5-9a1c-6c78bd920e3c.png)

**Comment by dylan-cromwell-sociomantic** [comment]
And finally version 2 alternates:

![hapijs-04](https://cloud.githubusercontent.com/assets/2911544/13649881/acf7db3e-e61e-11e5-80ec-186dee068880.png)

**Comment by dylan-cromwell-sociomantic** [comment]
As you can see she went for a very simplistic approach, @hueniverse. Let me know if I should pass any feedback to her or if it's even in the right direction at all.

And @zoe-1 I really like what you're doing with the logo ideas too! Very cool stuff, kudos!

**Comment by danielb2** [comment]
I like the cleverness of the smiley `;)`   :+1:

**Comment by meetthelegend** [comment]
Very nice @dylan-cromwell-sociomantic! I have another concept to throw into the mix as well. It also works off the smile concept, but I can also see parallels to the loop or cycle concept. // cc @hueniverse 

![hapi-logo-comps-02](https://cloud.githubusercontent.com/assets/4055156/13651988/bc471372-e5fe-11e5-99c6-c3bf862b330b.jpg)

![hapi-logo-comps-01](https://cloud.githubusercontent.com/assets/4055156/13651993/c377153e-e5fe-11e5-87ce-f37f663134c5.jpg)

![hapi-logo-comps-03](https://cloud.githubusercontent.com/assets/4055156/13651999/c9384c18-e5fe-11e5-898b-4b8e7dd7b3f9.jpg)

**Comment by meetthelegend** [comment]
![hapi-logo-comps-01](https://cloud.githubusercontent.com/assets/4055156/13651993/c377153e-e5fe-11e5-87ce-f37f663134c5.jpg)

**Comment by meetthelegend** [comment]
![hapi-logo-comps-03](https://cloud.githubusercontent.com/assets/4055156/13652142/6cbe9842-e5ff-11e5-98e2-6d7d34078e98.jpg)

**Comment by hueniverse** [comment]
@meetthelegend these are very cool but I am worried about trademark and brand issue (just take a look at https://www.google.com/search?q=happy+logo&tbm=isch).

@dylan-cromwell-sociomantic awesome! I need to think about feedback.

**Comment by adambrault** [comment]
@hueniverse I don't think there's any defensibility of the smile shape in a trademark. (See [trademark dilution](https://en.wikipedia.org/wiki/Trademark_dilution) — if you don't and can't defend a trademark as uniquely yours, you can't win any claim someone is infringing on your rights. Your example actually makes that point quite well in this case. :)

And hey, for example, here's [this story](https://boingboing.net/2008/03/28/walmart-loses-tradem.html): 

> "In its claims for trademark infringement against an online parodist, Wal-Mart claimed that it had trademark rights in the ubiquitous yellow smiley face. Not only did Wal-Mart lose its case, the judge held it had no rights in the smiley face mark."

**Comment by hueniverse** [comment]
@adambrault ok :-)

**Comment by adambrault** [comment]
@hueniverse Also: Hi, Eran. <3 <3 <3

**Comment by meetthelegend** [comment]
Thanks @hueniverse and @adambrault. I understand your concern (isn't branding fun?!) I'll throw any other ideas that come to mind into this issue, and maybe mock up how a new brand could look in the hapi website.

**Comment by dilkROM** [comment]
On vacation now but had to jump in to say big kudos @meetthelegend I love your design. This thread is a such a cool thing to see in the dev community when people come together and so much talent is shown off. Need more logo threads. :+1:

**Comment by dilkROM** [comment]
And @hueniverse sure thing, our designer is on stand-by if you have any requests or further instructions etc. Cheers!

**Comment by zoe-1** [comment]
In general, I like the work @meetthelegend and @dylan-cromwell-sociomantic are doing.
https://github.com/hapijs/contrib/issues/68#issuecomment-194499635 is my favorite of the above FWIW. Second would be https://github.com/hapijs/contrib/issues/68#issuecomment-194499744.
If a nodejs logo theme is preferred, then @meetthelegend 's designs would work. However, I prefer something different from the nodejs theme.

If I had all the votes and could just fiat the decision, I would create some sort of an abstract image or concept that represents hapi.  For example, previously the helmet with it's connection to Ren and Stimpy t.v. show was that (happy happy joy joy).  Additionally, I think of Walmarts logo and it's light bulb / shining light as an abstract image representing Walmart.  Github has the octocat etc. etc.  Even though there are famous brands that do not follow this concept (ex Google), I would prefer hapi to have an image concept that represents hapi and not just have it's name in pretty text or something like that. The name hapi leds itself to having a really fun logo as described above IMHO. The hapi face I submitted is my attempt at achieving this.  I am sure we can come up with better.  

Perhaps, we could turn the hapi face into a hapi robot named `hapibot`. And, `hapibot` could be the hapi mascot or something.  Anyhow, I am just brain storming with the community. 
Appreciate your thoughts. 

O yeah, if we are going to keep the helmet concept, then https://github.com/hapijs/contrib/issues/68#issuecomment-173352864 does the job IMHO.

It has been fun designing with the community :-) This thread has provided some nice breaks from coding. With all that said, below is another round of concepts...
<br/><br/>
![hapibubblegumplayorange](https://cloud.githubusercontent.com/assets/1852507/13797746/4e6cbdba-eae6-11e5-9436-96affe499959.png)
<br/><br/>
![hapibubblegumplayyellow](https://cloud.githubusercontent.com/assets/1852507/13797759/6bc8e550-eae6-11e5-9f37-db90e37cbedd.png)
<br/><br/>
![hapibubblegumplayred](https://cloud.githubusercontent.com/assets/1852507/13797774/76b1b208-eae6-11e5-8abf-925d3e01d8ed.png)
<br/><br/>
![hapibubblegumplayblue](https://cloud.githubusercontent.com/assets/1852507/13798218/62107fc4-eaea-11e5-9ac5-7ed5d68e63c1.png)

<br/><br/>
![hapibubblegumtempateplayred2](https://cloud.githubusercontent.com/assets/1852507/13797781/86733b80-eae6-11e5-9b97-0e3c4b7451ab.png)

**Comment by nlf** [comment]
i feel like @meetthelegend and [this set](https://github.com/hapijs/contrib/issues/68#issuecomment-194499869) from @dylan-cromwell-sociomantic are the only ones that really nail the "clean and professional" look. the majority of the others feel too overdone.

**Comment by dylan-cromwell-sociomantic** [comment]
@hueniverse here is another look from our designer. She said she has had some time to "explore the concepts a bit further" by playing with colors and product design.

![01_combined](https://cloud.githubusercontent.com/assets/2911544/13803621/5e9c93be-eb03-11e5-92a4-4df97ec36f6b.png)

![02_combined](https://cloud.githubusercontent.com/assets/2911544/13803626/655d7434-eb03-11e5-8272-9184cbfa29cf.png)

@zoe-1 thanks for the insight, ideas, and especially praise of our designer's work. I've passed all that on. Perhaps she will take a stab at a text-less version (more about iconography).

@nlf I believe the set you like is represented here in the second mock-up.

**Comment by dylan-cromwell-sociomantic** [comment]
@hueniverse and @meetthelegend I just realized my earlier comments were with my non-work account @dilkROM ... sorry if that caused any confusion! :fearful:

**Comment by dylan-cromwell-sociomantic** [comment]
@hueniverse further concepts from our Designer, just for variety:

![hapijslogo-withjs](https://cloud.githubusercontent.com/assets/2911544/13931988/413727da-ef63-11e5-88d7-fbedf8705e03.png)

![hapijslogo-withoutjs](https://cloud.githubusercontent.com/assets/2911544/13932000/4c4f8e46-ef63-11e5-983e-f959606601ea.png)

**Comment by dylan-cromwell-sociomantic** [comment]
Gentle nudge at @hueniverse (and others): any further feedback and / or updates here? Anything else you'd like to see from our designer (or the other designers present, for that matter)?

**Comment by hueniverse** [comment]
Is there an easy tool to setup a test vote? I'd like to see what are the top 3 logos people like and then maybe do a revision on those.

**Comment by dylan-cromwell-sociomantic** [comment]
@hueniverse TypeForm ( https://www.typeform.com/ ) is free to use and pretty good / easy. I would recommend that if you wanted to create a quick survey for people to fill out. I think it does allow you to add images as well. Once you create a survey you can share a link to it here and people could go vote and then you can easily view the resulting data afterward.

Hope it helps!

**Comment by hueniverse** [comment]
Voting to thin out the selection: https://www.surveymonkey.com/r/DR6YQ8T

**Comment by hueniverse** [comment]
Comments from survey takers:

1 They are all bad! 4/11/2016 6:40 PM
2 This mobile interface to too annoying to vote with for the only one I actually like. The others are meh. 4/11/2016 2:57 PM
3 4 makes me think of lisp 4/11/2016 7:03 AM
4 Terrible survey UI 4/10/2016 1:43 PM
5 in fact, no one is good... 4/10/2016 12:46 PM
6 Image 8 has a lot of meaning. The helmet is shaped as a cloud and the antennas are the connections/interfaces to
that cloud (I see it as the interfaces in UML). Could Web Services be described better? Also, it is for me the most
appealing logo. The other logos are a bit meaningless and ugly to me.
4/10/2016 3:20 AM
7 If 7 had a hint of color it could be killer. 4/9/2016 7:11 PM
8 4,7 - everything else is... yukkkk 4/9/2016 4:26 PM
9 Rest of them...meh 4/9/2016 3:14 PM
10 No 2 is good but reminds me an insurance company. 8 is too Reddit, This voting system in super confusing, I requires
to scroll back and forth a lot. It would be much easier to put a number corresponding to a logo next to a rank. #ux
@ykovzel
4/9/2016 2:47 PM
11 they are all horrible 4/9/2016 1:47 PM
12 7 and 8 looks good, the rest sucks. 4/9/2016 11:30 AM
13 please choose the best logo 4/9/2016 11:12 AM
14 Why change? The current one is much better than all of these. 4/9/2016 10:39 AM
15 9 would have ranked higher without the hanging smile or whatever it is on the h. 4/9/2016 10:23 AM
16 Seven would also potentially be a good favicon, is self contained and well proportioned. It has to be seven! 4/9/2016 10:03 AM
17 Keep the space helmet! 4/9/2016 9:20 AM
18 Yeah, but I'm really love current logo. 4/9/2016 8:51 AM
19 This ranking is exponential 4/9/2016 8:35 AM
20 Honestly, it's hard to rank beyond #7 and #2. Not a big fan of the direction any of the other logos are going.
Considering #7 was just a concept and it came out looking pretty good after a couple iterations, I'd love to see hapi
work with that designer if they're interested in remaining involved.
4/9/2016 8:25 AM
21 #8 by far! Still prefer the current logo. 4/9/2016 7:36 AM
22 3 & 6 are too loud and confusing. :( 8 seems like a spiritual successor. I also really like 2 because it's clean, simple
and it's a smile for happy (hapi)!
4/9/2016 6:49 AM
23 Don't see a need for a rebrand, love the existing as is... 4/9/2016 6:16 AM
24 Just keep the existing one! 4/9/2016 5:36 AM
25 Current! 4/9/2016 5:13 AM
26 Great feel to 7. 4/9/2016 5:04 AM
27 8 by a landslide 4/9/2016 5:03 AM
28 Keep the helmet. 4/9/2016 4:43 AM
29 image 8 - most professional and positive 4/9/2016 3:56 AM
30 They are all pretty awful bar 7 and 8. 7 is by far the best. The current one would be next and then 8 would be after that 4/9/2016 3:03 AM
31 The first one will fit in print better. I didn't even want to award the others points. 4/9/2016 3:00 AM
1 / 2
hapi.js Logo Survey (Phase I) SurveyMonkey
32 I like the current logo. 4/9/2016 2:20 AM
33 I think we're still lacking more "professional" choice in the selection, only 2 designers gave it a real shot. 4/9/2016 2:10 AM
34 Please, do NOT pick 3, 6 or 9. They are not even proper logos, won't work across different mediums (e.g. will fail in
print, if you ever decide to do a merch like t-shirt).
4/9/2016 2:04 AM
35 I don't like the rest :) 4/9/2016 1:44 AM
36 Number 8 is really awesome and still has a clue from last logo, which is good. 4/9/2016 1:38 AM
37 The current one is fine 4/9/2016 1:35 AM
38 Only 7 and 8 are worth mentioning and could be an alternative for the current one, I feel that the rest would be a step
backwards
4/9/2016 1:31 AM
39 current logo 4/9/2016 12:47 AM
40 You can't tell this from my answer but I like 7 about a million times more than any of the rest! 4/9/2016 12:27 AM
41 Image 7 just has that fantastic retro-futuristic feel to it, that aligns so well with the futuristic vision of hapi 4/9/2016 12:10 AM
42 Everything except image 7 and 8 is really horrible and difficult to order. I’d rather not choose any of them. 4/9/2016 12:03 AM
43 Thanks a ton for your passion to work on hapi! 4/8/2016 11:52 PM
44 It's got to be 7. Looks most professional whilst interesting. Also has most customisable potential and as its an
astronaut he's looking towards the future. The others are either too fiddly or look dated already.
4/8/2016 11:49 PM
45 I think these were all a bit on the boring side and not reflecting the fun of Hapi 4/8/2016 11:47 PM
46 I like the old logo, it's colorful cartoon style and non-formal font. Because formalism and strictness are not associated
with being happy for me.
4/8/2016 11:24 PM
47 The first logo is ?? 4/8/2016 11:23 PM
48 They are all not great, the current logo is fine. Why the need to rebrand? 4/8/2016 11:20 PM
49 this is a terrible poll... 4/8/2016 11:01 PM
50 3, 4, 6, 9 are equally unappealing to me 4/8/2016 10:54 PM

**Comment by hueniverse** [comment]
Full results:

![image](https://cloud.githubusercontent.com/assets/56631/14538833/8589325c-0232-11e6-9218-fb65b000afba.png)

**Comment by nlf** [comment]
so 7 and 8 it sounds like are on top? which were those?

**Comment by hueniverse** [comment]
![logos](https://cloud.githubusercontent.com/assets/56631/14538847/9bdc3608-0232-11e6-9012-ff3526ff225b.jpg)

**Comment by jamesdixon** [comment]
Seems like your next project should be to develop a new hapi-based survey tool :)

@hueniverse did anyone ask you to fill out a creative brief or anything? Not sure that from this thread that it's clear what hapi means to you and where you see its future heading. Might be helpful in crafting a new logo/refining the existing entries.

**Comment by hueniverse** [comment]
@jamesdixon This is not my decision. I just think it's time for a cleaner logo that is moving away from Ren and Stimpy since we no longer follow that concept.

**Comment by hueniverse** [comment]
From twitter replies:

7 - 32 votes
8 - 16 votes
5 - 5 votes
2 - 3 votes
6 - 1 vote

**Comment by hueniverse** [comment]
Conclusion - people like the helmet.

I'll start a new thread for helmet logos so this thread doesn't get crazy long.

**Comment by digitalforus** [comment]
Hello! I would like to redesign the logo and give it a perfect and minimal look with simple animation
