### ISSUE TITLE
Walmart and LICENSE

### ISSUE THREAD

**Issue by Marsup** [hapijs/contrib#69]
Hello,

Received a PR updating the LICENSE (https://github.com/hapijs/joi/pull/801), not being a legal expert, I'm wondering whether they should be included in future copyright holders.

Is there anything I should know about any legal ties with Walmart that would force me to keep them in ? What should the LICENSE say from now on since they clearly disengaged from the project ?

/cc @hueniverse

**Comment by kpdecker** [comment]
#66 discusses this a bit

**Comment by Marsup** [comment]
A search for license obviously didn't bring this one, thanks :)
