### ISSUE TITLE
Style rule: "Empty line after {"

### ISSUE THREAD

**Issue by leesei** [hapijs/contrib#70]
The bullet point only give two situations:
* Following a multi-line condition
* In function scope declarations

But fat arrow function no longer create new scope.
```js
    execute(123, (err) => {

        console.log(err);
    });
```

We should add "In arrow function declarations" to it.

**Comment by hueniverse** [comment]
Just create a PR for the style doc.

**Comment by prashaantt** [comment]
A little tangential to this issue: I've been deferring to the hapi style guide for some time but I just noticed the "Arrow function bodies must be enclosed in curly braces" rule. That takes away the beauty of implicit returns you get without the braces, and is therefore a sacrifice of a native JS feature for style. It shouldn't be enforced, IMHO.

**Comment by skeggse** [comment]
@prashaantt idk I personally dislike non-void implicit returns

**Comment by leesei** [comment]
@prashaantt @skeggse care to move the discussion to #72?
