### ISSUE TITLE
Tools/utilities that don't fit as plugins

### ISSUE THREAD

**Issue by danielb2** [hapijs/contrib#76]
I wrote a tool called [hapi-runplugin](https://www.npmjs.com/package/hapi-runplugin) specifically to easily list what endpoints are returned by running a given plugin. When things are organized in different repos and they are re-used and it's not always sensible to test something via a server, this comes in handy.

Regardless, the webpage has a plugins section, but no section for tools. A composer like Glue is a tool like this which also has value.

I've noticed that Glue can easily be overlooked, so this would solve that.

thoughts?

**Comment by Marsup** [comment]
Certainly, though this issue might be better on hapijs.com repo :)

**Comment by danielb2** [comment]
sure ;)
