### ISSUE TITLE
Use discourse as a discussion board?

### ISSUE THREAD

**Issue by paulovieira** [hapijs/contrib#79]
Discourse is now offering free hosting for successful open-source projects like hapi. More details here:

http://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/

I think using a discourse-based forum for hapi would improve the discussions at several levels. They have evolved greatly in the last 2 years. It's a very robust product.  If you are not familiar with it, check out the introduction here: https://www.discourse.org/faq/

**Comment by Marsup** [comment]
I don't see much of an advantage to it compared to what we already use.

**Comment by mtharrison** [comment]
I agree with @Marsup.

**Comment by paulovieira** [comment]
Discourse is a modern discussion platform. Github issues are fine, but they feel essentially like the typical php board from the 2000's.

I could enumerate the advantages of using Discourse but I would be repeating what has been said before in other places. The initial page at discourse.org shows some of the functionalities and the (About page)[http://www.discourse.org/about/] has more details. A good way to understand why moving to discourse would improve the discussion is to try it for a little bit. Check this discussion from the Ember board, for instance:

http://discuss.emberjs.com/t/why-is-ember-3x-5x-slower-on-android

Some of the cool stuff that is possible with Discourse:

- It's easier to find the most interesting topics (using several means such as number of views and likes, or the "Top" listing). And for a long topics (with say 50 replies or more), it's easier to find the most relevant replies (using the "summarize this topic" button).
- When you open a topic, it shows suggested topics in the right (similar in content to what you are reading).
- When you start writing a new topic, it detects if the content is similar to other existing topics and alerts the user (avoid repeated discussions).

There are many more cool things. Check the about page. And new cool things are added in each new version. Discourse is getting better and better.

**Comment by devinivy** [comment]
On the other hand it would create inconsistency with how we track issues.  Discourse genuinely does seem cool, and I'm glad to have taken a look at it thanks to this issue– but it also seems like a solution to several problems that we don't have, at the cost of introducing the complexity of an additional tool to our contributors and users.  I'll keep my eye on it, though– it might work well for other projects.

**Comment by paulovieira** [comment]
Not sure how it would create inconsistency. Isn't hapijs/contrib being used as a discussion board, for stuff like "I don't understand how to use realms" ? In fact I think it would make more sense to have the kind of content we have here in a separate plataform.

I agree with you with that Discourse would bring more complexity: we would have one more thing to manage (although it shouldn't be that much of problem since it's a hosted solution with free and automatic upgrades). That being said, I volunteer to make the bridge and set up the necessary configuration (placing the logo, etc), as I already have experience using it.

It's also true that Discourse works best for large discussions with dozens of participants. For small topics with 3 or 4 replies the benefits are not that visible. Even then I think it's better than using github issues.

It would be cool to hear some more people about this.

**Comment by Marsup** [comment]
The thing is, most of the knowledge is on github, we need to cross reference related issues, that's not an option in discourse. While I agree issues are not great, they're the only one to do that.

**Comment by paulovieira** [comment]
Closing this issue. The majority of people who expressed their opinion didn't think discourse would be a good fit for the hapi community.
