### ISSUE TITLE
Plans for Node v6?

### ISSUE THREAD

**Issue by cjihrig** [hapijs/contrib#80]
Node 6 is scheduled to be released this month. Since it is the next LTS release, I assume it will be supported. What versions of Node will be supported once 6 comes out? Is there going to be another round of breaking releases to pick up new ES6 features?

**Comment by Marsup** [comment]
I'd say the way we switched to v4 was a clean cut, we'll get complains anyway but I don't see a better process.

**Comment by vdeturckheim** [comment]
Will there be any new major features in addition to the ones from [v8 4.9](http://v8project.blogspot.fr/2016/01/v8-release-49.html) ?

**Comment by nlf** [comment]
v4 LTS is supported until 4/18. IMO we should support it until then.

**Comment by Marsup** [comment]
@nlf are you saying you want us to only use v4 features until then or break from it but backport security fixes only ?

**Comment by nlf** [comment]
i'd be fine with backporting security fixes to a version of hapi supporting node 4, but i also don't feel like a breaking change to depend on node 6 just for the sake of supporting node 6 has any merit.

until we reach the point that 6 has a feature we need/want to leverage we should carry on supporting 4. when that happens, we bump the major version of hapi and continue backporting security fixes to the previous major.

**Comment by devinivy** [comment]
This makes a lot of sense to me.  The change from v0.10 to v4 was different for several of reasons.  That said, I think at least all hapi core repos should act more or less in unison.

**Comment by Marsup** [comment]
Well I'd use destructuring and default parameters for one. Also the change on Math.random() might have security implications, but I'm no crypto expert.

**Comment by hueniverse** [comment]
We are pretty much done with the node 0.10 LTS (v9.x) branch. With node v6 out, it will be the new baseline for hapi and node v4 the new LTS for hapi. Once hapi core uses features in node v6, we will follow the same process as we did with hapi v10 with a node-only breaking release. At that point we'll get all the deps to move up as well.

Note that once we move to node v6, we will no longer support node v5, only v4 as LTS.

The LTS support in hapi is pretty much exclusive for security updates and we never had that much of those.

Let's wait for v6 to come out, give it a few weeks, see how all our code is testing against it (travis is already set for v4 and latest).

**Comment by gergoerdosi** [comment]
Now that v6 is out, what are the next steps? I can dedicate some time to help with the move. What are the tasks?

**Comment by hueniverse** [comment]
First is getting lab to work on it. Then each hapi core module needs to test on it.

**Comment by gergoerdosi** [comment]
I think lab already works with v6:
https://github.com/hapijs/lab/commit/c7dd9744c08c45d93231381d5964c76bfb181c85

Testing means updating lab and `.travis.yml`? In case of `travis.yml`, should `6` be explicitly specified, or is it enough to have `latest`?

**Comment by geek** [comment]
Lab already supports node v18.0.0

<img src="http://i.imgur.com/kQO9cli.png" />


I will go through and test/open issues for other modules if I find any with the latest.  I am using `- 6` in travis.

**Comment by hueniverse** [comment]
Travis should be set to "4" and "6" only.
