### ISSUE TITLE
Wordpress provider

### ISSUE THREAD

**Issue by pankajpatel** [hapijs/contrib#81]
Hello,

I needed the wordpress provider for my project, so I have created one at [https://github.com/pankajpatel/bell](https://github.com/pankajpatel/bell).

Please review it.

**Comment by Marsup** [comment]
Belongs to the bell repo, not here.

**Comment by AdriVanHoudt** [comment]
@pankajpatel open up a PR to the bell repo, they will be happy to review your changes there
