### ISSUE TITLE
New Helmet Logo Design (part II)

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#82]
We started looking at replacing the current logo with a new one. We collected 9 designs and did a survey. Two logos where the clear favorites: 7 and 8 (see #68).

![logos](https://cloud.githubusercontent.com/assets/56631/14539124/e10c205c-0233-11e6-9455-c80d53f8c26b.jpg)

I would like to see if anyone would like to post a few more revisions of the helmet logo, new or building on the work in 7 and 8. Once we get those over the next few weeks, we'll do one last survey with them and the existing logo and see which one people want to use moving forward.

**Comment by paulrad** [comment]
7 for me

**Comment by hueniverse** [comment]
Please do not vote any more, especially not in this thread. This is to discuss ideas and post new logos. We are not voting on a new logo right now. Any votes will be deleted.

**Comment by kkemple** [comment]
This is a rough, but I like the idea of a more anonymous helmet, and I liked the antenna from on the sides from 8, this is what I came up with. It feels a bit round to me but with some updates it could be much better.

![hapi-logo](https://cloud.githubusercontent.com/assets/3629876/14541781/a63cf7c8-0259-11e6-9445-d0c1dd5faefc.jpg)

**Comment by kolodny** [comment]
Does it make sense to turn each choice into a separate comment so people can :+1: the ones they like?

**Comment by hueniverse** [comment]
@kolodny we are not voting, just brainstorming. The goal is not to express preference but ideas on how to make things better or try new directions.

**Comment by gavriguy** [comment]
can you pleae explain or direct me to a link for why we want to change the logo in first place? 

changing a logo is a matter of both reaon and timing, and i would love to  understand if the logo change is a part of a more internal change in hapi.

**Comment by Marsup** [comment]
@gavriguy the reasons are already in #68 which this thread is a follow-up to.

**Comment by jhrobles** [comment]
![hapi-revised](https://cloud.githubusercontent.com/assets/10146684/14623483/89d2b434-0587-11e6-9570-ef0d755e8a5a.png)

Here's a revision of 8

**Comment by AdriVanHoudt** [comment]
I like the font but would make the helm a bit wider

**Comment by haldrix** [comment]
And what about putting the helmet over the "A" and use the right antenna to complete the dot above the "i" ?

**Comment by kkemple** [comment]
i would like to see the helmet a bit wider as well, good concept tho!

here is space helmet in hexagon...

![hapi-logo](https://cloud.githubusercontent.com/assets/3629876/14648569/f10e8566-0630-11e6-9619-dce6f774ef7c.jpg)

**Comment by kkemple** [comment]
im interested to know if anyone is in to this idea or not

**Comment by kkemple** [comment]
@jhrobles what font is that?

**Comment by jamesdixon** [comment]
@kkemple personally, I think that helmet is too much of a void. The black lens is a bit overwhelming and seems to consume everything around it; even without the 'hapi' text.

**Comment by jamesdixon** [comment]
@vctrfrnndz any new thoughts on your take on the hapi helmet? I believe it's probably the strongest of all the concepts.

**Comment by kkemple** [comment]
@jamesdixon thanks for the feedback, i also feel it could use some love, trying it out with type next to it, to see if that helps, have another idea as well im working on...

![hapi-logo-layouts](https://cloud.githubusercontent.com/assets/3629876/14648942/c6718e5a-0632-11e6-98bc-6d30474b1d07.jpg)

**Comment by johnbrett** [comment]
I think if we are to change the logo and sticking with helmets, I would go with something closer to the logos in 7 or 8. They look more friendlier and welcoming IMO which is more representative of the hapi community. I prefer the flat design too!

**Comment by vctrfrnndz** [comment]
@hueniverse Any suggestion on what to improve if going in 7 direction? What are the pain points? :)

**Comment by hueniverse** [comment]
My motivation in looking for a new logo is to make things simpler, more icon and less illustration. It would be nice to keep the helmet but simplify it. Beyond that, I rather not push into any specific direction.

**Comment by Cortrah** [comment]
hey guys,

I stumbled onto this this week and late last night tried a few variations entirely based on other folks stuff. They are not very good but some some grist for the mill and hopefully together with some ideas to get folks thinking about this again.

I really like the look of the space helmet by Victor and love the ways it could be reused visually with motion. If you choose it I promise to any motion graphics for for anyone who wants such a thing.

It clearly works on the hapi homepage better than anything else. Something that replaces the illustration needs more than just a glyph, two other contexts to consider are github organization badges and how it relates to the other projects icons. I'd rather the person be a cat or a chiwawa to represent that this is a progression of hapi, sending cats and dogs into into outer space, very serious stuff.

I really like the way that jhrobles helmet relates to the old one which I love and also, in it's simpler form it reminds me of hapi's modular plugin architecture where each node coming off the helmet could be joi or lab or good. I could definitely see the helmet glyphs as the begining of a component architecture diagram where each glyph has a slightly fun cartoon aspect, while still rooted in a professional relationship to one another.

I thought some of the other folks ideas were very creative, in particular with how one part relates to another and if given a spatial layout to work within some of those other ideas might really combine to accentuate the whole.

If I were to suggest a process it would be for a technical person, maybe Matt Harrison who's book I've been reading and led me here, and who seems to have a good talent for diagramming concepts to create a technical diagram that illustrates how a full fledged hapi app were to connect the various pieces. Then we break the thing up into pieces and do fun treatments on each piece for the components that relate to a character or two in victor's helmets communicating via the antennae.

Feel free to ignore, but I wanted to suggest. If I have time at some point I'll put together a schematic as an example and see if it prompts some more thought or feedback from folk who know the framework better than I do.

![bleedy_helmet](https://cloud.githubusercontent.com/assets/8292986/15794438/b3139660-29b8-11e6-80cf-b0bf229aa1ab.png)

![space_helmet](https://cloud.githubusercontent.com/assets/8292986/15794437/b313b60e-29b8-11e6-878c-699b5377333d.png)

![helmet](https://cloud.githubusercontent.com/assets/8292986/15794436/b3138012-29b8-11e6-852e-bd4ec782e3d9.png)

**Comment by Cortrah** [comment]
So a question: if hapi were to have a diagram on it's front page of how some of it's most important plugins were to inter-relate, what would they be?  I think my thought would be a lot easier for folk to work with if I can create a good first pass to think about.
At a bare minimum, I"m thinking
Hapi
glue
confidence
boom
lout
nes
good
tv
hoek
joi
an authentication cluster with a sub-diagram for basic vs oz
lab and code

I'm struggling for perspective though as I'm still just learning

**Comment by dilkROM** [comment]
@hueniverse discussion seemed to trail off. Is there still a need to change the logo?

Also, bit confused, as at first the brief we gave to our designer was that it should not include a helmet due to moving away from the Ren & Stimpy reference. Has this changed?

Cheers! :)

**Comment by hueniverse** [comment]
@dilkROM I still think the logo should be updated to something else. I am not sure there is community consensus around it, and I don't have the bandwidth to lead this effort. If someone else from the hapi core team wants to take lead and guide this process, that would be great. Otherwise, I think we are stuck with the current logo. I am going to propose a new Community Lead role that if works out could help with this.

**Comment by wwalser** [comment]
I found this thread because I was interested in what the license is for the current (and future) logo. Thinking of getting stickers/temporary tattoos printed, wanted to know if there were hoops to jump through.

**Comment by hueniverse** [comment]
The logo is under the same license as the code.

**Comment by calmdev** [comment]
Here's a suggestion &mdash; keep the existing helmet and change the color scheme between major releases. Choose a primary color from the scheme, use it as a replacement for the yellow on [hapi's website](https://hapijs.com/). Same logo, minimal effort and new colors make it feel fresh each major version by giving the _appearance_ of a new helmet.

![untitled](https://user-images.githubusercontent.com/461249/28493068-7d66ed12-6edd-11e7-8733-4fa5239dcdcd.png)
![hapi-logo-1](https://user-images.githubusercontent.com/461249/28493096-236b98de-6ede-11e7-9270-bc4682c3aabf.png)

**Comment by toxicmender** [comment]
I don't know if anyone else thought this,but logo no.7 (Astronaut helmet) sort of reminded me of Postman. Logo no.8 is nice, someone said it reminded them of reddit but i think that's just the tilted antenna at the top.

**Comment by iagocalegari** [comment]
Here's another suggestion. I tried something cleaner and a kind of more organic helmet.
![hapijs_1](https://user-images.githubusercontent.com/18454350/54883711-4f348f80-4e47-11e9-8afe-c6a00267a310.png)

**Comment by hueniverse** [comment]
@iagocalegari interesting direction. I am going to be restarting logo discussions soon.

**Comment by Nargonath** [comment]
@iagocalegari yeah nice suggestion, I like it.

**Comment by hueniverse** [comment]
I think this would be better just decided by me... design by committee is just not working out ;-)
