### ISSUE TITLE
New lint rule for case sensitive module loading

### ISSUE THREAD

**Issue by geek** [hapijs/contrib#86]
@hapijs/owners any objections to me adding a couple of lint rules to our hapi style:

1 - Enforce that module loading is case sensitive

```
// Right
const Hoek = require('hoek');

// Wrong
const Hoek = require('Hoek');
```

2 - Require `.json` when loading a json file:

```
// Right
const Package = require('./package.json');

// Wrong
const Package = require('./package');
```

**Comment by nlf** [comment]
definite +1 to the first (case sensitivity has bitten us several times developing in OSX and deploying to Linux), the second i'm completely neutral on

**Comment by devinivy** [comment]
@geek is this for hapijs/owners or the broader hapijs/core-project-maintainers?

In any case, I like both those rules.

**Comment by geek** [comment]
@devinivy really, anyone :) I didn't want to spam everyone.

**Comment by johnbrett** [comment]
I'm totally on board with both - first one has bitten me too, just like @nlf.

Curious how the first one works though. Does it compare the name vs that in the package.json or something?

**Comment by Marsup** [comment]
Modules can only be lowercase.

**Comment by kanongil** [comment]
Actually, modules can have any case. In practice this is restricted by the npm repository which only allows lowercase names for new modules.

Note that there exists legacy non-lowercase modules on npm. Eg. [AMD](https://www.npmjs.com/package/AMD) vs. [amd](https://www.npmjs.com/package/amd).

**Comment by Marsup** [comment]
My bad, thought they cleaned it up when they set up the new rules.

**Comment by johnbrett** [comment]
@kanongil, that's exactly why I'm curious how it's implemented, there's still stuff like: https://www.npmjs.com/package/JSONStream on npm!

**Comment by nlf** [comment]
Also local requires are occasionally mixed case for us
