### ISSUE TITLE
Issues template

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#87]
Can someone with some free time come up with a standard issues template we can deploy across the entire org, and one for hapi core to tell people to go to discuss for questions?

**Comment by AdriVanHoudt** [comment]
I think the one from node it pretty good https://raw.githubusercontent.com/nodejs/node/master/.github/ISSUE_TEMPLATE.md

**Comment by Marsup** [comment]
I wondered myself about that when I introduced it to joi, I don't think we all have the same expectations regarding what to provide in an issue. But there might be some common ground on a few things.

**Comment by arb** [comment]
Yeah I'm not totally sold on GH issues being able to be standardized in a meaningful way across the org. The things people have issues with in Joi are going to be wildly different than issues people have with TV for example.

**Comment by mtharrison** [comment]
I think we should at least have one for hapijs/hapi mainly to push people to ask general stuff in hapijs/discuss.
