### ISSUE TITLE
Node v6 support status

### ISSUE THREAD

**Issue by gergoerdosi** [hapijs/contrib#88]
I'm creating this issue to track node v6 support for the hapi modules.
## Repositories

Repositories that have "node" or "6" in their `.travis.yml`:
- [x] accept
- [x] ammo
- [x] b64
- [x] bassmaster
- [x] bell
- [x] boom
- [x] bossy
- [x] call
- [x] catbox
- [ ] catbox-memcached (Status: requires a refactor, Lead Maintainer: @chapel)
- [x] catbox-memory
- [x] catbox-mongodb
- [x] catbox-redis
- [x] chairo
- [x] code
- [x] confidence
- [x] content
- [x] crumb
- [x] cryptiles
- [ ] faketoe (Status: requires a refactor, Lead Maintainer: @nlf)
- [x] glue
- [x] good
- [x] good-broadcast (Status: waiting for release, Lead Maintainer: @lloydbenson)
- [x] good-console
- [x] good-file
- [x] good-http
- [x] good-squeeze
- [x] good-udp (Status: waiting for release, Lead Maintainer: @ulrikaugustsson)
- [x] h2o2 (Status: waiting for release, Lead Maintainer: @osukaa)
- [x] hapi
- [x] hapi-auth-basic
- [x] hapi-auth-cookie (Status: waiting for release, Lead Maintainer: @jaw187)
- [ ] hapi-auth-hawk (Status: requires a refactor, Lead Maintainer: @dannycoates)
- [x] heavy
- [x] hoek
- [x] inert
- [x] isemail
- [x] items
- [x] joi
- [x] kilt
- [x] lab
- [x] lout
- [x] mimos
- [x] nes
- [x] nigel
- [x] oppsy
- [x] peekaboo
- [x] pez
- [x] poop
- [x] rejoice
- [x] reptile
- [x] scarecrow
- [x] scooter (Status: waiting for merge, PR: https://github.com/hapijs/scooter/pull/33, Lead Maintainer: @danielb2)
- [x] shot
- [x] statehood
- [x] subtext
- [x] topo
- [x] tv (Status: waiting for merge, PR: https://github.com/hapijs/tv/pull/130, Lead Maintainer: @osukaa)
- [x] vise
- [x] vision (Status: waiting for release, Lead Maintainer: @jagoda)
- [x] visionary
- [x] wreck
- [x] yar
## Travis

I noticed that the version numbers used in `.travis.yml` are inconsistent. The most common ones are:

``` yml
node_js:
  - "4"
  - "6" 
```

``` yml
node_js:
  - "4"
  - "node" 
```

But there are repositories with "5" or "stable". Some repositories were not updated for a while, they include version numbers like "0.10", "0.12", or even "iojs".

I think we should agree on a template and repositories should follow that. Actually the question is whether to use "6" or "node" in addition to "4".
## Updates

I will try to keep this list updated, but feel free to update the list if you have access to do so. Also, if I made a mistake (a module supports v6 but I didn't mark it), let me know and I will update the list.

**Comment by gergoerdosi** [comment]
In issue #80 @hueniverse said (https://github.com/hapijs/contrib/issues/80#issuecomment-217355798) to use "4" and "6", so I went ahead and started to open pull requests.

**Comment by hueniverse** [comment]
Great!

**Comment by AdriVanHoudt** [comment]
@gergoerdosi this is awesome! If possible we could link to the PR's created for clarity?

**Comment by vdeturckheim** [comment]
@gergoerdosi Great work !
There is a [PR on good-upd](https://github.com/hapijs/good-udp/pull/34) updating to the latest good version + es6 refactor + travis targets updates

**Comment by gergoerdosi** [comment]
@vdeturckheim: Great! Updated the status:

@AdriVanHoudt: Good suggestion. Added the PRs and also the lead maintainers, so we can immediately see who we needs to do some work.

**Comment by nlf** [comment]
is "waiting for release" relevant if the only change required was adding node 6 to the travis config? i don't think updating CI configuration is worth publishing a new version over IMO

**Comment by cjihrig** [comment]
Agree with @nlf, that's why I hadn't published some of mine after updating.

**Comment by hueniverse** [comment]
If the published version passes tests, no need for a new one just for CI.

**Comment by gergoerdosi** [comment]
True. Hapi's shrinkwrap is set to patch versions, so it's enough that the latest release works on v6. I will mark those modules done then.

**Comment by hueniverse** [comment]
However, if you change tests or anything in package.json, I would publish a minor version just to keep things clean.

**Comment by gergoerdosi** [comment]
I went through the list again, but it's not easy to decide whether a module can be considered ready for v6. For some it was clear, if the only commit after the latest release was the v6 test, then I marked it as ready. But there are modules that have a lot of change since the last release, for example b64, good-broadcast, h2o2, or isemail. I kept the requires release note there. The last one, isemail, is special, package.json has been updated with version 2.1.1 and 2.1.2, but the latest release on npm is 2.1.0.

**Comment by devinivy** [comment]
@gergoerdosi updated lab for me in topo.  Does that merit a release per @hueniverse?
> However, if you change tests or _anything in package.json_

**Comment by gergoerdosi** [comment]
The list should be complete now. PRs were submitted to all repositories that didn't have v6 in `travis.yml`. Where the status says "waiting for release", either a `dependency` was updated, or there were other code changes since the last release.

**Comment by devinivy** [comment]
You deserve a medal :)

**Comment by hueniverse** [comment]
Statehood fails the tests now because of something that changed in v6. I don't have time to dig into it but it looks like the prototype doesn't match between the parsed cookies object and the plain object passed in the tests in some deep equal checks.

**Comment by gergoerdosi** [comment]
Yes, I noticed that too. Already working on it. The prototypes are easy to fix (can be disabled in `expect()`). However looks like one test case uses deep equal for object comparison, and a message in that object is different on v4 and v6. Need to figure out how to test it the best way. I will try to come up with a PR soon.

**Comment by AdriVanHoudt** [comment]
Is there a reason nothing is noted behind hapi itself?

Also any maintainers looking for PR's, as long as it is not super complex (since I don't know all the modules) I am happy to help out!

**Comment by gergoerdosi** [comment]
Hapi comes last. Eran wrote in https://github.com/hapijs/contrib/issues/80#issuecomment-217254197:

> First is getting lab to work on it. Then each hapi core module needs to test on it.

Of course we don't need to wait for all modules to be updated, the list looks already good. But there are a still few direct dependencies of hapi that are not tested, for example peekaboo or statehood (the latter works, just need to fix the tests). And there are a few popular modules that I think should be tested too before we can say hapi is compatible with v6, for example glue, h2o2, or vision.

Anyway, added a status to hapi too.

**Comment by hueniverse** [comment]
I am going to wait for code v3 on all hapi dependencies before I move hapi to v6.

**Comment by cjihrig** [comment]
@hueniverse I can publish code v3 right now. Are you OK with the current state of it for v3?

**Comment by hueniverse** [comment]
@cjihrig yep. It does all I want.

**Comment by cjihrig** [comment]
Published. Good luck with your tests everyone :trollface:

**Comment by hueniverse** [comment]
Sweet!

**Comment by geek** [comment]
@cjihrig lab is now updated and published with the latest... no issues with moving to code v3.

**Comment by hueniverse** [comment]
Core is done and published under v13.4.1. Go use your fancy node v6.

**Comment by cadecairos** [comment]
I've just pushed out [v2.0.0 of bassmaster](https://github.com/hapijs/bassmaster/releases/tag/v2.0.0), supporting node 4 and 6, with full test coverage.

**Comment by gergoerdosi** [comment]
Quick update:

- 51 of 63 modules support node v6. :tada:
- 7 modules just require a release (@stongo, @lloydbenson, @ulrikaugustsson, @osukaa, @jaw187, @Marsup, @jagoda).
- 2 modules have a PR that is waiting for merge (@danielb2, @osukaa).
- 3 modules require an ES 6 refactor (@chapel, @nlf, @dannycoates).

Thanks for all the maintainers for their support!

**Comment by lostthetrail** [comment]
@gergoerdosi Scooter PR has been merged and released as 4.0.0.

**Comment by x37v** [comment]
been a while since there has been an update here.. any news with the v6 status?

**Comment by gergoerdosi** [comment]
I'm not working for the company anymore where we used hapi, so I'm not following the changes either. If somebody wants to take over the maintenance of the list feel free to do so, maintainers are able to check / uncheck items. Otherwise I suggest to close this issue.
