### ISSUE TITLE
Exclude non lib files form packages

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#90]
I think it time to change our .npmignore policy and reduce package sizes. Thoughts?

**Comment by geek** [comment]
Agreed... we should ignore everything except `lib` and `package.json`.

**Comment by Marsup** [comment]
Already doing it on joi, that was ~10x improvement in size. Someone said on gitter that keeping API.md would be helpful when you're offline, that's not much of a sacrifice to keep.

**Comment by arb** [comment]
I like what you did with joi to keep .gitignore in sync with .npmignore using the npmignore tool.

**Comment by hueniverse** [comment]
I don't think we should keep any docs with the npm package. If people want the docs they should grab the docs.

**Comment by mark-bradshaw** [comment]
Great idea.  I've implemented this on yar and accept.

**Comment by geek** [comment]
The `.npmignore` file can be made to be very simple:

https://github.com/hapijs/reptile/blob/master/.npmignore

```
*
!lib/
```

**Comment by arb** [comment]
I like @geek's suggestion. That's nice and clean.

**Comment by nlf** [comment]
i like @geek's solution too, nice and portable

**Comment by cjihrig** [comment]
@geek is my hero

**Comment by nlf** [comment]
@geek is a hero to us all

**Comment by Marsup** [comment]
That doesn't work for me on joi, only index is included.
But that does:
```
*
!lib/**
```

**Comment by arb** [comment]
I can confirm @Marsup. I tried this on another module and the only file under "lib" that was included was "index.js".

**Comment by devinivy** [comment]
Should the license travel with the code for good measure?

**Comment by cjihrig** [comment]
There are some files that are never ignored, including the license. See https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package.

**Comment by ldesplat** [comment]
Despite what the documentation says what I run `npm pack` with marsup's `.npmignore` the README.md file is never included but LICENSE is. Do any of you have the same issue? And will it properly show up in npmjs.org?

**Comment by Marsup** [comment]
The readme is there for me, which version of npm ?

**Comment by skeggse** [comment]
I thought the readme get tossed into the package.json, no?

**Comment by ldesplat** [comment]
node v6.2.1
npm 3.9.3
Trying to update to 3.9.5

Definitely not included in the package.json in `npm pack` at least.

**Comment by Marsup** [comment]
Works with 3.8.6. Definitely a bug with npm.

**Comment by ldesplat** [comment]
You are right: https://github.com/npm/npm/issues/12876 which then links all the way back to a 2014 issue :)

So, be careful, if you're publishing with node 6 and npm 3.9.3 (or 3.9.5) for that matter.
As soon as you exclude a file starting with `.` or you use the wildcard match, it will exclude the README :(

**Comment by ldesplat** [comment]
This worked for me in node 6... unfortunately includes the .npmignore file but oh well.
```
*
!lib/**
!.npmignore
```
