### ISSUE TITLE
Pre-commit hook to ensure test coverage on all the projects

### ISSUE THREAD

**Issue by dgonzalez** [hapijs/contrib#94]
Hi, not sure if it is something that you want to have but... there is the possibility of using the package "pre-commit" to fire up a pre-commit hook that runs the tests and coverage to ensure with Lab that the baseline for the coverage is met.

Is it something that you will be open to?

**Comment by AdriVanHoudt** [comment]
You are talking about hapi org repos right? I think most of them have a CI set up to test these things when someone opens a PR.
For example check https://github.com/hapijs/hapi/commits/master you can see the crosses and checkmarks for all the builds indicating that tests and coverage are (not) ok.

**Comment by Marsup** [comment]
Unnecessary complexity I think. Code either enter the code base through PRs or direct maintainer commits. Both have CI and I'd count on the maintainers to be responsible.

**Comment by AdriVanHoudt** [comment]
Apart from complexity, I use this internally and this is not supper windows/faul proof ^^
