### ISSUE TITLE
Testing plugin across hapi versions

### ISSUE THREAD

**Issue by jonathansamines** [hapijs/contrib#95]
Hi all, recently I have been developing a couple of internal hapi plugins for my company internal usage. 

However, I was trying to test my new plugin versions across a set of hapi versions (different hapi versions are used on different applications). So my question is, there is an automated way to do so? Or I should I manually test on each supported?

Thanks for your help!

**Comment by cjihrig** [comment]
Check out https://github.com/hapijs/bell/blob/6b664a86875c301fb5dcd950fe514c69308be633/.travis.yml if you're using Travis.

**Comment by jonathansamines** [comment]
@cjihrig Unfortunately My build process runs on a custom jenkins pipeline. So I am not able to use it to run my plugin tests in different environments :(

**Comment by cjihrig** [comment]
If it's a custom pipeline, then you should have even more flexibility. `npm install hapi@$HAPI_VERSION` is the key command to testing different versions of hapi.

**Comment by jonathansamines** [comment]
I see how should I handle this now. Thanks to pointing that out @cjihrig
