### ISSUE TITLE
Adding non-code contributors

### ISSUE THREAD

**Issue by Marsup** [hapijs/contrib#96]
Testing waters here, how do core contributors feel about welcoming people in the organization that are not code contributors but rather support people that have already shown devotion to the project(s). This might be a good way to help them help us on triaging, and also an acknowledgment of their work.

**Comment by nlf** [comment]
i like the idea. people who answer questions are super valuable

**Comment by devinivy** [comment]
I agree– it sounds good to me.  It grants community-related privileges (i.e. enables useful github features, like labeling issues) those folks might not otherwise have.

**Comment by mark-bradshaw** [comment]
I'm somewhat ambivalent, but I'm not a great question answerer. :)  I have no particular beef with it.

**Comment by Marsup** [comment]
@mark-bradshaw I guess you'd have to be OK with them sometimes labeling or even closing issues on your own project, there's nothing final about it obviously but that might still be something to consider.

**Comment by mark-bradshaw** [comment]
I'm perfectly fine with labeling.  Closing...  I guess I'm willing to see if it becomes an issue.  I expect they'll exercise the same respect that all the other org members do.

**Comment by Marsup** [comment]
Well if you're watching your own repo, it shouldn't be a problem seeing those closed ones.

**Comment by Marsup** [comment]
The idea seems to be mostly accepted. How do you think we should proceed now ? Throw in names and vote ? Since we're talking about people, I'm wondering if we should do this through secret ballot, I want people to feel comfortable saying no without hurting anyone. WDYT ?

**Comment by arb** [comment]
Where/how can we do a secret ballot?

**Comment by Marsup** [comment]
http://poll.gitrun.com might be an option, GH login, anonymous results, but you can't restrict to org only I guess, I'm also not sure how it stores the votes, if it sends a +1 in your stead, that's useless. We could also vote with emojis in a private repo but I don't think we have that, do we ? Also it's not that secret. Open to proposals or comments. Do you think we sometimes need a debate about the people or just plain yes/no ?

**Comment by thebergamo** [comment]
Maybe using an secret chat room in gitter?

**Comment by Marsup** [comment]
It's harder to "thread" discussions (if there's the need) in a chat. That could be an option since we already have that, I'm just not sure everyone is OK with going on Gitter, I know not all contributors are there.

**Comment by arb** [comment]
I think the people who'd actually participate would be ok with just a "yes/no"

**Comment by hueniverse** [comment]
I think you look at who is already doing the work, run their names by a few other core contributors and just add them.

**Comment by Marsup** [comment]
So @AdriVanHoudt is the 1st (of hopefully many others) to be in that team, warm welcome to him !
If you feel uncomfortable giving him permissions on your repo just let me know and I'll see if github's permissions can deal with that.
Feel free to candidate or suggest names would fit.

**Comment by AdriVanHoudt** [comment]
Thanks for thinking of me, it is a real honor! 🎆 
If there is stuff I should know about labeling or anything specific for your/all repos just let me know!
I'm also the easiest to reach on the Gitter if you need me or want to talk to me. (or any medium you like really ^^)

I'm not planning on doing anything code related atm but yeah if you feel uncomfortable about the permission stuff let @Marsup know, don't want to cause any troubles/bad feelings :O

**Comment by devinivy** [comment]
Awesome, welcome @AdriVanHoudt :)  This is a good doc to check-out https://github.com/hapijs/contrib/blob/master/Guidelines.md

**Comment by AdriVanHoudt** [comment]
@devinivy nice, will read it!

**Comment by johnbrett** [comment]
Welcome @AdriVanHoudt 👍

**Comment by nlf** [comment]
this has been done and acted on so i'm going to close the issue :+1:
