### ISSUE TITLE
Community Lead role

### ISSUE THREAD

**Issue by hueniverse** [hapijs/contrib#97]
For the most part, core components of the framework are well maintained and issues are addressed in a timely manner with steady releases. However, we have a few org plugins and initiatives that seem to have leadership issues. In the past, I would routinely review org repos and ping maintainers to see if they still have the time to lead or if we should seek someone else. I was also paid full time to support non-code initiative like the mentorship program.

At this point, my time is limited to keeping the core module in good shape. Everything else is beyond my bandwidth. I have hoped for others to step forward and take leadership but I also understand that as long as I'm seen as the project head, no one else would try to step forward and take charge.

To solve this, I would like to suggest we create a new core contributor lead role which will be elected by the full core and community contributors to basically lead the community for a year at a time. The role will be largely defined by the person performing it, but keeping things going smoothly, making sure projects are maintaining the hapi.js quality we learned to expect, handling issues such as the new logo, etc. are obvious goals.

We don't need to write special bylaws since this is basically covered by the existing rules. The Community lead will be a core contributor, with the same powers as any other core contributor. However, I think the title and core lead status will give them the authority to guide the community, poke idle leads, and facilitate progress.

We can formalize this a bit more if people feel it is necessary.

I think a good way to move forward with this is to write a few questions for candidate to answer as part of the election process which will ask them to explain how they view the role and its goals as well as to demonstrate they have the resources (namely, an employer supporting the effort which can take a couple days a week to perform) to do the job.

Thoughts?

**Comment by hueniverse** [comment]
One note - I was asked in the past about moving hapi.js into the node foundation. While I don't have a strong opinion on the matter, my concern (and objection) has always been around the ability to keep the BDFL model under the foundation. As the lead maintainer of the core framework module, I have no intentions of giving up my BDFL status and to be able to make all final decision about the core code base. I don't know where things stand with the foundation at this point, but any discussion about moving this org to be more closely tied to another organization must take this into account.

**Comment by cjihrig** [comment]
+1 to adding a community lead.

I don't *think* the foundation is still trying to umbrella all the things, but in general, I really prefer hapijs as a standalone org.

**Comment by mark-bradshaw** [comment]
If Eran wants someone else to step up into a leadership role, then I'm in support of the notion of a community lead.  I think there's some very active core contributors who would likely do a good job.

**Comment by arb** [comment]
@hueniverse any ideas what these questions would look like? As the current person in the position, your input here would be valuable.

**Comment by hueniverse** [comment]
1. If you were elected, what would you focus on? How would you support the community? What issues you think are the top priority?
2. Do you have the support of your employer to spend significant amount of time on hapi community leadership?
3. What makes you qualified for this role? Why should people vote for you?

If someone who doesn't want this job wants to help facilitate this process, that would be great.

**Comment by nlf** [comment]
Soooo, I don't *yet* have time for this, but I will starting at the end of January. I would love to take on this role starting then.

1.

> If you were elected, what would you focus on? How would you support the community? What issues you think are the top priority?

If I were elected I would focus on education. The majority of the issues that we see opened seem to be related to poor and/or missing documentation, examples and tutorials. I'd like to put some effort into revamping the site and bolstering the tutorials section, as well as adding in and fleshing out the "cookbooks" section that was proposed some time ago. I also think bringing back some more interactive learning methods would be a good way to bring people up to speed, whether it's freshening up makemehapi or the hapi university.

2.

> Do you have the support of your employer to spend significant amount of time on hapi community leadership?

I have the support of my employer to take this on. &yet has historically been a big supporter of hapi, as well as an early adopter. We use hapi every day, so contributing to this effort is a big win for us.

3.

> What makes you qualified for this role? Why should people vote for you?

I was the first non-walmart employee to become a core contributor. I (with a *lot* of help from @thefoxis) built the initial version of the current site and secured hosting for it. I wrote the majority of the existing tutorials. I was an active participant of the mentorship program when it was still going. I've also been a member of the irc channel (remember when we still used that?) for ages, and was one of the first people in the gitter channel. I've been around for a while. Also, I like helping, it's my favorite.

A mushroom walks in to a bar, the bartender looks him over and says "hey buddy, we don't serve your kind around here!". The mushroom replies "why not? i'm a fungi!"

A vote for nlf is a vote for puns. Thank you.

**Comment by devinivy** [comment]
I also really like the idea of a community lead, and I'm excited that we have at least one great option on the table in @nlf (which means that this is really going to happen!).  A little bit of news from my neck of the woods– the company I work for, Big Room Studios, is evaluating if they can swing supporting this in the upcoming year (we really would love to!), so there may be another candidate before long.  I will update this thread when I know more!

**Comment by arb** [comment]
Personally, I think whoever it is should have buy in from their company, so that's good to hear @devinivy and @nlf.

**Comment by devinivy** [comment]
Unfortunately it sounds like we can't support the role at this time, but we will be carving out more hours to support hapijs and its ecosystem in general.  I'm personally rallying for time to support some of hapijs's educational programs/materials, so perhaps we could coordinate with whomever becomes the community lead to help bolster that endeavor.  I hope we didn't stall this process too much!  I will try to stay on top of this issue and make sure it moves along.

Are there any places we should ensure this position is advertised?  I forget if it's on twitter, I don't think it's mentioned in hapijs/discuss.  Are there any takers aside from @nlf?  Are there any more questions you all are interested to ask?

**Comment by hueniverse** [comment]
I am skeptical the right person for this role is not already following this repository. You kinda have to be involved to be able to do this, especially as the first person to hold the position. I would wait until the end of the month to allow anyone else to nominate themselves. After that, we will hold an election. If there is only one candidate, we'll skip the vote counting part...

**Comment by AdriVanHoudt** [comment]
@devinivy it is really great to hear that your company is dedicated to the hapi community and I think that whoever takes the role would be very grateful with all the help!

**Comment by hueniverse** [comment]
I'd like to thank @nlf for stepping up and offering to take on this role. I know he will be a great community lead.
