### ISSUE TITLE
Conflict in rules for object assignment 

### ISSUE THREAD

**Issue by saeidalidadi** [hapijs/contrib#99]
In `style.md` there is two rules for object assignment which deny each other. the two are as bellow:

- No inline object in assignment unless empty.
- No space for empty objects {}

**Comment by thebergamo** [comment]
I can't figure how on deny other. 

* No inline object in assignment unless empty. 
If the object aren't empty, you need to assign it using this form:
``` javascript
const obj = {
    a: 1
};

const emptyObj = {};
```
This code above are agree with the two rules.

* No space for empty objects {}
Remove spaces inside brackets when the object is empty.
``` javascript
// don't use
const obj = { };

// use 
const obj = {};
```

For me the rules are correct.

**Comment by saeidalidadi** [comment]
@thebergamo I mean the line:
```javascript
const user = { name: 'john', email: 'john@example.com' };
```
Is this true for this rule?  `No inline object in assignment unless empty.`

**Comment by thebergamo** [comment]
Well, in this case isn't true. Because when you're assigning an object to a variable is recommended you not using an inline object. 
The correct statement is: 
``` javascript
const user = {
    name: 'john',
    email: 'john@example.com'
};
```

Inline objects are used in just two cases, when you're sending as an option in a function not assign for a variable, or assign an empty object to a variable.

**Comment by nlf** [comment]
the confusion here is that the line

`const user = { name: 'john', email: 'john@example.com' };`

is there to demonstrate the spacing rule, *not* to show that it's appropriate to define an object this way. i agree, it's a bit confusing. we can change it to be a function call instead, which is acceptable per style guidelines.
